Repository mesosphere/konvoy-image-builder, pull requests merged in 2021-08, with the labels that each got.

#52 chore: add preflight checks
  .golangci.yml
  Makefile
  ansible/_validate.yaml
  ansible/group_vars/all/system.yaml
  ansible/roles/validate/tasks/main.yaml
  ansible/validate.yaml
  cmd/konvoy-image/cmd/validate.go
  docs/cli/konvoy-image.md
  docs/cli/konvoy-image_validate.md
  go.mod
  go.sum
  pkg/app/validate.go
Labels: enhancement

#69 bug: fix overrides
  cmd/konvoy-image/cmd/generate.go
Labels: bug

#70 feat: adds instance type override option to build app
  cmd/konvoy-image/cmd/args.go
  pkg/app/build.go
  pkg/packer/manifests/aws/packer.json.tmpl
Labels: enhancement

#66 feature: nvidia flatcar gpu
  ansible/molecule/ec2_full/converge.yml
  ansible/molecule/ec2_full/molecule.yml
  ansible/roles/gpu/files/Dockerfile.libnvidia
  ansible/roles/gpu/tasks/nvidia-gpu-Flatcar.yaml
  ansible/roles/gpu/templates/etc/nvidia-container-runtime/config.toml
  ansible/roles/gpu/templates/etc/systemd/system/nvidia-flatcar.service
  ansible/roles/gpu/templates/usr/libexec/oci/hooks.d/oci-nvidia-hook
  ansible/roles/gpu/templates/usr/share/containers/oci/hooks.d/oci-nvidia-hook.json
  ansible/roles/packages/templates/etc/systemd/system/containerd-flatcar.service
  ansible/vars/flatcar/flatcar.yaml
  pkg/packer/manifests/aws/packer.json.tmpl
Labels: do not merge

#81 fix: set docker containerd shim socket
  Makefile
  ansible/vars/flatcar/flatcar.yaml
Labels: bug
