Repository mesosphere/konvoy-image-builder, pull requests merged in 2021-12, with the labels that each got.

#151 fix: flatcar gpu build fix for kernel 5.10.80.
  ansible/roles/gpu/files/nvidia-driver
Labels: bug

#152 fix: prevents use of cgroupsv2 for flatcar gpu
  ansible/roles/gpu/tasks/nvidia-gpu-Flatcar.yaml
Labels: bug

#155 fix: update for upcoming linter bump
  .textlint-whitelist.yaml
  .textlintrc
  docs/nvidia-gpu.md
Labels: documentation

#194 chore: remove duplicate Makefile code and add overrides
  Makefile
Labels: ignore-for-release
