Repository mesosphere/konvoy-image-builder, pull requests merged in 2022-04, with the labels that each got.

#277 feat(azure): add additional images
  goss/goss.yaml
  images/azure/flatcar.yaml
  images/azure/oracle-7.yaml
  images/azure/oracle-8.yaml
  images/azure/rhel-7.yaml
  images/azure/rhel-8.yaml
  images/azure/sles-15.yaml
Labels: feature

#299 fix: support flatcar 3033.2.0
  ansible/roles/containerd/tasks/flatcar.yaml
  ansible/roles/gpu/tasks/nvidia-gpu-Flatcar.yaml
  images/ami/flatcar.yaml
Labels: fix

#307 fix: use bastion in offline fips ova rhel builds
  Makefile
Labels: fix

#300 feat: use containerd with flatcar
  Makefile
  ansible/roles/containerd/tasks/flatcar.yaml
  ansible/vars/flatcar/flatcar.yaml
Labels: feature

#313 chore(ansible): remove unused file
  ansible/molecule/ec2_gpu/converge.yaml
  ansible/provision.yaml
  ansible/vars/centos/centos-7.yaml
Labels: ignore-for-release

#296 fix(azure): always ensure image definitions
  Makefile
  pkg/app/build.go
Labels: fix

#297 chore(make): reorg build targets and add Azure
  Makefile
  cmd/konvoy-image/cmd/aws.go
  cmd/konvoy-image/cmd/azure.go
  docs/cli/konvoy-image_build.md
  docs/cli/konvoy-image_build_aws.md
  docs/cli/konvoy-image_build_azure.md
  docs/cli/konvoy-image_generate.md
  docs/cli/konvoy-image_generate_aws.md
  docs/cli/konvoy-image_generate_azure.md
  images/azure/rhel-8.yaml
  make/ci.mk
  make/images.mk
  pkg/app/build.go
  pkg/app/config.go
  pkg/app/constants.go
  test/e2e/scripts/clean-last-azure-image.sh
  test/infra/aws/Makefile
  test/infra/aws/export.sh
  test/infra/vsphere/Makefile
  test/infra/vsphere/export.sh
Labels: ignore-for-release

#321 chore(devkit): fix python packages
  Dockerfile
  Dockerfile.devkit
  requirements-devkit.txt
  requirements.txt
Labels: ignore-for-release

#322 chore(nvidia): update repo signing keys
  ansible/roles/gpu/defaults/main.yaml
  ansible/roles/gpu/tasks/nvidia-gpu-Ubuntu20.yaml
Labels: ignore-for-release
