Repository mesosphere/konvoy-image-builder, pull requests merged in 2022-09, with the labels that each got.

#491 docs: nits for grammar and style
  Makefile
  docs/dev/gcp.md
Labels: documentation

#492 fix: create RHEL 8 base template without root and default user's password
  .gitignore
  pkg/packer/manifests/vsphere/base/.env.sample
  pkg/packer/manifests/vsphere/base/README.md
  pkg/packer/manifests/vsphere/base/linux/centos/http/7/ks.cfg
  pkg/packer/manifests/vsphere/base/linux/centos/http/8/ks.cfg
  pkg/packer/manifests/vsphere/base/packer-base.json
  pkg/packer/manifests/vsphere/base/rhel-7-base.json
  pkg/packer/manifests/vsphere/base/rhel-8.4-base.json
  pkg/packer/manifests/vsphere/base/run.sh
  pkg/packer/manifests/vsphere/base/vsphere-base.json
Labels: fix

#499 fix: create base centos 7.9 template without default password
  pkg/packer/manifests/vsphere/base/linux/centos/http/7/ks.cfg
  pkg/packer/manifests/vsphere/base/packer-base.json
  pkg/packer/manifests/vsphere/base/rhel-7.9-base.json
  pkg/packer/manifests/vsphere/base/rhel-8.4-base.json
Labels: fix

#497 fix: centos does not need RHSM. Fix ansible conditions
  ansible/roles/repo/tasks/redhat.yaml
  ansible/roles/sysprep/tasks/redhat.yml
Labels: fix

#498 feat: authenticate to vsphere base template using ssh private key and ssh auth agent.
  .gitignore
  ansible/roles/sysprep/tasks/main.yml
  images/ova/rhel-79.yaml
  images/ova/rhel-84.yaml
  pkg/packer/manifests/vsphere/packer.json.tmpl
  test/infra/vsphere/packer-vsphere-airgap.yaml.tmpl
Labels: feature

#483 chore(main): release 1.21.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#482 feat: install nvidia driver using runfile
  ansible/group_vars/all/defaults.yaml
  ansible/roles/config/templates/config.toml.tmpl
  ansible/roles/gpu/defaults/main.yaml
  ansible/roles/gpu/files/blacklist-nouveau.conf
  ansible/roles/gpu/files/nvidia-persistenced.sh
  ansible/roles/gpu/tasks/nvidia-gpu-CentOS7.yaml
  ansible/roles/gpu/tasks/nvidia-gpu-RHEL.yaml
  ansible/roles/gpu/tasks/nvidia-gpu-RHEL7.yaml
  ansible/roles/gpu/tasks/nvidia-gpu-RHEL8.yaml
  ansible/roles/gpu/tasks/nvidia-gpu-SLES15.yaml
  ansible/roles/gpu/tasks/nvidia-gpu-Ubuntu20.yaml
  ansible/roles/gpu/tasks/nvidia-gpu.yaml
  ansible/roles/gpu/templates/etc/nvidia-container-runtime/config.toml
  ansible/roles/gpu/templates/etc/systemd/system/nvidia-driver.service
  ansible/roles/gpu/templates/etc/systemd/system/nvidia-persistenced.service
  ansible/roles/offline/tasks/upload.yaml
  cmd/konvoy-image/cmd/artifacts.go
  docs/cli/konvoy-image_upload.md
  docs/cli/konvoy-image_upload_artifacts.md
  make/ci.mk
  make/images.mk
  overrides/offline-nvidia.yaml
  pkg/app/artifacts.go
Labels: feature

#500 fix: bump mindthegap to preserves image IDs
  Dockerfile.devkit
Labels: fix

#503 fix: upgrade ansible to 6.3.0 and fix CI flakes
  Dockerfile.devkit
  ansible/requirements.txt
  ansible/roles/packages/tasks/debian.yaml
  ansible/roles/providers/tasks/azure-pip.yml
  hack/pip-packages/pip-getter/Dockerfile
  pkg/packer/manifests/aws/packer.json.tmpl
  pkg/packer/manifests/azure/packer.json.tmpl
  pkg/packer/manifests/gcp/packer.json.tmpl
  requirements.txt
  test/infra/vsphere/packer-vsphere-airgap.yaml.tmpl
Labels: fix

#501 chore(main): release 1.22.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#458 fix: ubuntu for vsphere
  ansible/roles/providers/tasks/vmware.yml
Labels: fix

#510 fix: incorrect RHEL when condition
  ansible/roles/repo/tasks/redhat.yaml
  ansible/roles/sysprep/tasks/redhat.yml
Labels: fix

#509 chore: release 1.23.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#511 fix: upload nvidia runfile for offline preprovisioned
  ansible/roles/offline/tasks/upload.yaml
  pkg/app/artifacts.go
Labels: fix

#512 chore(main): release 1.23.1
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending
