Repository mesosphere/konvoy-image-builder, pull requests merged in 2022-02, with the labels that each got.

#226 fix: wires extra vars correctly
  cmd/konvoy-image/cmd/args.go
  cmd/konvoy-image/cmd/generate.go
  cmd/konvoy-image/cmd/provision.go
  docs/cli/konvoy-image_build.md
  docs/cli/konvoy-image_generate.md
  docs/cli/konvoy-image_provision.md
  pkg/app/build.go
Labels: fix

#229 chore: Retry more SLES tasks to work around connectivity issues
  ansible/roles/gpu/tasks/nvidia-gpu-SLES15.yaml
Labels: ignore-for-release

#231 fix: configure NetworkManager to prevent interfering with interfaces
  Makefile
  ansible/roles/networking/tasks/main.yaml
Labels: fix

#233 fix: create systemd drop-in to make NetworkManager-cloud-setup service no-op
  CHANGELOG.md
  ansible/roles/networking/tasks/main.yaml
  ansible/roles/packages/tasks/install-redhat.yaml
Labels: fix

#240 fix(lint): fix linting errors by configuration
  .github/linters/.markdown-lint.yml
  .github/linters/.textlint-whitelist.yaml
  .markdown-lint.yml
  .textlint-whitelist.yaml
  .textlintrc
  CHANGELOG.md
Labels: fix

#239 feat: create vsphere template image for RedHat 8.4 and 7.9
  .gitignore
  Makefile
  ansible/roles/providers/tasks/vmware.yml
  ansible/roles/repo/tasks/redhat.yaml
  ansible/roles/sysprep/tasks/redhat.yml
  docs/dev/README.md
  docs/dev/vsphere.md
  images/ova/rhel-79.yaml
  images/ova/rhel-84.yaml
  pkg/packer/manifest.go
  pkg/packer/manifests/packer.go
  pkg/packer/manifests/vsphere/base/linux/centos/http/7/ks.cfg
  pkg/packer/manifests/vsphere/base/linux/centos/http/8/ks.cfg
  pkg/packer/manifests/vsphere/base/linux/rhel
  pkg/packer/manifests/vsphere/base/packer-base.json
  pkg/packer/manifests/vsphere/base/rhel-7-base.json
  pkg/packer/manifests/vsphere/base/rhel-8-base.json
  pkg/packer/manifests/vsphere/base/vsphere-base.json
  pkg/packer/manifests/vsphere/packer.json.tmpl
Labels: feature
