Repository mesosphere/konvoy-image-builder, pull requests merged in 2022-10, with the labels that each got.

#493 fix: Configure containerd runc plugin options with systemd cgroup driver
  ansible/roles/config/templates/config.toml.tmpl
  ansible/roles/containerd/tasks/install-flatcar.yaml
Labels: fix

#520 fix: force register RHSM
  ansible/roles/repo/tasks/redhat.yaml
Labels: fix

#521 fix: disable unnecessary linters
  .github/workflows/lint.yml
Labels: fix

#518 feat: Add toml-merge image for containerd supplementary images
  ansible/group_vars/all/defaults.yaml
  ansible/roles/images/tasks/main.yaml
Labels: feature

#530 feat: add RHEl 8.6 base template
  pkg/packer/manifests/vsphere/base/linux/centos/http/8/ks.cfg
  pkg/packer/manifests/vsphere/base/rhel-8.6-base.json
Labels: feature

#532 fix: add retries when installing SUSE packages
  ansible/roles/containerd/tasks/suse.yaml
  ansible/roles/packages/tasks/suse.yaml
  ansible/roles/providers/tasks/googlecompute.yml
  ansible/roles/providers/tasks/qemu.yml
  ansible/roles/providers/tasks/vmware.yml
  ansible/roles/sysprep/tasks/suse.yml
Labels: fix

#531 feat: build AMI and OVA for RHEL 8.6 networked, nvidia and airgapped flavors
  ansible/roles/packages/tasks/redhat.yaml
  ansible/roles/sysprep/tasks/redhat.yml
  images/ami/rhel-86.yaml
  images/ova/rhel-86.yaml
  make/ci.mk
  make/images.mk
Labels: feature

#534 fix: add kuberentes version to azure gallery image name
  cmd/konvoy-image/cmd/azure.go
  docs/cli/konvoy-image_build_azure.md
  docs/cli/konvoy-image_generate_azure.md
  pkg/app/build_azure.go
  pkg/app/config.go
  pkg/app/config_test.go
  pkg/azure/azure.go
Labels: fix

#538 fix: nvidia override files with correct information
  overrides/nvidia.yaml
  overrides/offline-nvidia.yaml
  pkg/app/config_test.go
  pkg/app/constants.go
Labels: fix

#516 fix: remove fips.configure from a user facing override
  ansible/group_vars/all/system.yaml
  overrides/fips.yaml
Labels: fix

#515 fix: remove fips.configure from a user facing override
  overrides/fips.yaml
Labels: fix

#522 chore(main): release 1.24.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#539 build: sync CLI docs to Confluence
  .github/workflows/sync-cli-docs.yaml
Labels: github_actions, ignore-for-release, build

#545 fix: add image_name and kubernetes_version to all infrastructure's outtput manifest.yaml
  pkg/packer/manifests/azure/packer.json.tmpl
  pkg/packer/manifests/vsphere/packer.json.tmpl
Labels: fix

#544 build: enable Nvidia offline for rhel 8.6
  make/ci.mk
  make/images.mk
Labels: enhancement, feature

#547 fix: fips.configure default value
  ansible/roles/fips/tasks/main.yaml
Labels: fix

#550 fix: set feature flag for cloud-init to ignore errors
  ansible/molecule/default/molecule.yml
  ansible/molecule/default/tests/test_default.py
  ansible/roles/providers/tasks/misc.yml
  ansible/roles/repo/defaults/main.yaml
Labels: fix, needs-backport

#551 fix: set feature flag for cloud-init to ignore errors
  ansible/molecule/default/molecule.yml
  ansible/molecule/default/tests/test_default.py
  ansible/roles/providers/tasks/misc.yml
  ansible/roles/repo/defaults/main.yaml
Labels: fix

#558 chore: release 1.24.1 (see PR description)
  README.md
Labels: ignore-for-release
