Repository mesosphere/konvoy-image-builder, pull requests merged in 2022-08, with the labels that each got.

#452 fix: add overrides, work-dir, and extra-args flags to upload artifacts
  cmd/konvoy-image/cmd/args.go
  cmd/konvoy-image/cmd/artifacts.go
  docs/cli/konvoy-image_upload_artifacts.md
  pkg/app/artifacts.go
  pkg/app/build.go
  pkg/app/build_test.go
  pkg/app/config.go
  pkg/app/utils.go
Labels: fix

#454 chore(main): release 1.19.8
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#455 fix: remove mark inventory file as required
  cmd/konvoy-image/cmd/artifacts.go
Labels: fix

#456 chore(main): release 1.19.9
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#467 chore: make override offline file for aws consistent
  test/infra/aws/export.sh
  test/infra/aws/packer-aws-offline-override.yaml.tmpl
Labels: ignore-for-release

#451 feat: move disabling swap and firewalld to a shared play
  ansible/roles/kubeadm/tasks/main.yaml
  ansible/roles/sysprep/tasks/main.yml
Labels: feature

#473 fix: upgrade azure packages to 1.x.x and golang to 1.18
  .github/workflows/golangci-lint.yml
  .github/workflows/lint.yml
  .github/workflows/release-tag.yaml
  go.mod
  go.sum
  pkg/azure/azure.go
Labels: fix

#426 feat: bump Ansible to 4.10.0
  Dockerfile.devkit
  ansible/requirements.txt
  requirements.txt
Labels: feature

#469 fix: remove builder user in sysprep
  ansible/roles/sysprep/tasks/main.yml
Labels: fix

#468 feat: bump kubernetes version to 1.24.4
  ansible/group_vars/all/defaults.yaml
  images/common.yaml
Labels: feature

#470 feat: add cloudendpoint to azure flags
  cmd/konvoy-image/cmd/azure.go
  docs/cli/konvoy-image_build_azure.md
  docs/cli/konvoy-image_generate_azure.md
  pkg/app/build_azure.go
  pkg/app/config.go
  pkg/app/config_test.go
  pkg/app/constants.go
  pkg/azure/azure.go
  pkg/packer/manifests/azure/packer.json.tmpl
Labels: feature

#474 feat: disable password ssh auth
  ansible/roles/sysprep/tasks/main.yml
Labels: feature

#472 chore: release 1.20.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#459 fix(azure): support dry run in image creation
  Dockerfile.devkit
  ansible/roles/providers/tasks/azure-pip.yml
  make/images.mk
  pkg/packer/manifests/azure/packer.json.tmpl
  test/e2e/scripts/clean-last-azure-image.sh
Labels: docker, fix

#476 feat: import container images with mindthegap
  .dockerignore
  Dockerfile
  Dockerfile.devkit
  ansible/group_vars/all/defaults.yaml
  ansible/roles/images/tasks/load.yaml
  ansible/roles/offline/tasks/upload.yaml
  make/images.mk
Labels: feature
