Repository mesosphere/konvoy-image-builder, pull requests merged in 2022-11, with the labels that each got.

#552 fix: use environment variables to authenticate with base vsphere template
  cmd/konvoy-image-wrapper/cmd/wrapper.go
  cmd/konvoy-image-wrapper/cmd/wrapper_test.go
  images/ova/rhel-79.yaml
  images/ova/rhel-84.yaml
  images/ova/rhel-86.yaml
  pkg/packer/manifests/vsphere/packer.json.tmpl
Labels: fix

#559 fix: Can not specify custom Packer directory
  pkg/packer/manifests/aws/packer.json.tmpl
  pkg/packer/manifests/azure/packer.json.tmpl
  pkg/packer/manifests/gcp/packer.json.tmpl
  pkg/packer/manifests/vsphere/packer.json.tmpl
Labels: fix

#560 chore: remove RHEL 8.2 image definition and Makefile targets
  ansible/molecule/ec2_full/molecule.yml
  ansible/molecule/ec2_gpu/molecule.yml
  docs/dev/nvidia-gpu.md
  images/ami/rhel-82.yaml
  make/ci.mk
  make/images.mk
Labels: ignore-for-release

#554 chore: use konvoy image wrapper for build targets
  .goreleaser.yml
  Dockerfile
  Dockerfile.devkit
  Makefile
  README.md
  cmd/konvoy-image-wrapper/cmd/wrapper.go
  cmd/konvoy-image-wrapper/cmd/wrapper_test.go
  cmd/konvoy-image-wrapper/main.go
  cmd/konvoy-image/cmd/gcp.go
  make/ci.mk
  make/images.mk
  test/infra/vsphere/packer-vsphere-airgap.yaml.tmpl
Labels: ignore-for-release

#546 chore(main): release 1.24.1
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#566 fix: use old add user command
  Dockerfile.devkit
Labels: fix

#573 fix: use new centos 7.9 base AMI
  images/ami/centos-79.yaml
Labels: fix, needs-backport

#578 chore(main): release 1.24.2
  CHANGELOG.md
Labels: do not merge, ignore-for-release, autorelease: pending

#581 fix: add oracle7 fips target
  make/images.mk
Labels: fix

#586 fix: use upstream centos 7
  images/ami/centos-79.yaml
Labels: fix

#587 fix: use upstream centos 7
  images/ami/centos-79.yaml
Labels: fix

#584 fix: Configure containerd runc plugin options with systemd cgroup driver
  ansible/roles/config/templates/config.toml.tmpl
  ansible/roles/containerd/tasks/install-flatcar.yaml
Labels: fix

#585 fix: Configure containerd runc plugin options with systemd cgroup drivers
  ansible/roles/config/templates/config.toml.tmpl
  ansible/roles/containerd/tasks/install-flatcar.yaml
Labels: fix

#579 feat: upgrade kubernetes version to 1.25.4
  ansible/group_vars/all/defaults.yaml
  ansible/roles/version/tasks/main.yaml
  ansible/roles/version/templates/kubeadm-conf.yaml.tmpl
  images/common.yaml
Labels: feature

#583 chore(main): release 1.25.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#574 docs: adding bit about custom amis
  docs/dev/changing-amis.md
Labels: documentation

#593 fix: propogate signals to packer sub-command
  pkg/packer/packer.go
Labels: fix

#592 fix: Enable fs.may_detach_mounts kernel parameter on RHEL 7.9, and variants
  ansible/roles/containerd/tasks/install.yaml
Labels: fix
