Repository mesosphere/konvoy-image-builder, pull requests merged in 2022-03, with the labels that each got.

#252 fix: use crictl to pull images and supports mirrors
  ansible/roles/images/tasks/check-or-pull-images.yaml
Labels: fix

#253 docs: nits on grammar and fixing links
  README.md
  docs/dev/README.md
  docs/dev/add-new-os.md
  docs/dev/nvidia-gpu.md
  docs/dev/vsphere.md
Labels: documentation

#259 chore: remove pulling kfips image
  ansible/group_vars/all/defaults.yaml
Labels: ignore-for-release

#251 feat: allow user to run ssh communicator through bastion
  .gitignore
  Makefile
  hack/configure-vsphere-bastion.yaml
  hack/vsphere/main.tf
  images/ova/rhel-79.yaml
  images/ova/rhel-84.yaml
  pkg/app/config.go
  pkg/packer/manifests/aws/packer.json.tmpl
  pkg/packer/manifests/vsphere/packer.json.tmpl
  test/infra/vsphere/Makefile
  test/infra/vsphere/export.sh
  test/infra/vsphere/packer-vsphere-airgap.yaml.tmpl
Labels: feature

#262 chore: use k8s image bundles from S3
  Makefile
  ansible/list-images.yaml
  hack/save-images.sh
Labels: ignore-for-release

#264 feat: added centos79-fips
  Makefile
Labels: feature

#230 feat: support azure
  Dockerfile.devkit
  Makefile
  cmd/konvoy-image-wrapper/cmd/wrapper.go
  cmd/konvoy-image/cmd/azure.go
  cmd/konvoy-image/cmd/build.go
  cmd/konvoy-image/cmd/generate.go
  docs/cli/konvoy-image_build.md
  docs/cli/konvoy-image_build_azure.md
  docs/cli/konvoy-image_generate.md
  docs/cli/konvoy-image_generate_azure.md
  go.mod
  go.sum
  images/azure/centos-7.yaml
  pkg/app/build.go
  pkg/app/config.go
  pkg/app/config_test.go
  pkg/app/constants.go
  pkg/app/errors.go
  pkg/azure/azure.go
  pkg/packer/manifest.go
  pkg/packer/manifests/azure/packer.json.tmpl
  pkg/packer/manifests/packer.go
Labels: feature

#270 fix: go-mod tidy
  .github/super-linter.env
  go.mod
  go.sum
Labels: fix

#157 feat: bump k8s to 1.22.8
  ansible/group_vars/all/defaults.yaml
  ansible/group_vars/all/system.yaml
  ansible/roles/repo/tasks/suse.yaml
  ansible/roles/version/tasks/main.yaml
  ansible/roles/version/templates/kubeadm-conf.yaml.tmpl
  images/common.yaml
  overrides/fips.yaml
Labels: feature

#271 fix(ansible): allow rsa public keys
  Dockerfile
  Dockerfile.devkit
  pkg/packer/manifests/aws/packer.json.tmpl
  pkg/packer/manifests/azure/packer.json.tmpl
  pkg/packer/manifests/vsphere/packer.json.tmpl
Labels: bug, fix

#283 fix: cleanup vsphere VM when building vSphere template in dry run
  Dockerfile.devkit
  pkg/packer/manifests/vsphere/packer.json.tmpl
Labels: fix

#285 fix: makefile targets for NVIDIA GPU support
  Makefile
Labels: fix

#287 fix: fixes version lock to set fact
  ansible/roles/containerd/tasks/redhat.yaml
  ansible/roles/containerd/tasks/suse.yaml
  ansible/roles/kubeadm/tasks/redhat.yaml
  ansible/roles/packages/tasks/redhat.yaml
  ansible/roles/packages/tasks/suse.yaml
  ansible/roles/setup_versionlock/tasks/redhat.yaml
  ansible/roles/setup_versionlock/tasks/suse.yaml
Labels: fix

#289 fix(packer): fix spacing typo in packer template
  pkg/packer/manifests/azure/packer.json.tmpl
Labels: fix
