Repository mesosphere/konvoy-image-builder, pull requests merged in 2022-06, with the labels that each got.

#373 feat: install googlecompute packer plugin
  Dockerfile
  Dockerfile.devkit
  cmd/konvoy-image/cmd/gcp.go
  docs/cli/konvoy-image_build_gcp.md
  images/gcp/centos-79.yaml
  make/ci.mk
  make/images.mk
Labels: feature

#382 chore: change vsphere datastore to local disks
  images/ova/rhel-79.yaml
  images/ova/rhel-84.yaml
Labels: ignore-for-release

#385 fix: upload command flag
  cmd/konvoy-image/cmd/artifacts.go
Labels: fix

#387 feat: bump versions of k8s to 1.23.7
  ansible/group_vars/all/defaults.yaml
  images/common.yaml
  test/e2e/ansible/testdata/ansible/roles/echo/tasks/main.yaml
Labels: feature

#393 fix: use the same instance-type as konvoy
  cmd/konvoy-image/cmd/azure.go
  docs/cli/konvoy-image_build_azure.md
  docs/cli/konvoy-image_generate_azure.md
  pkg/packer/manifests/azure/packer.json.tmpl
Labels: fix

#398 fix: GCP bugs and minor improvements
  cmd/konvoy-image-wrapper/cmd/wrapper.go
  cmd/konvoy-image/cmd/gcp.go
  docs/cli/konvoy-image_build_gcp.md
  images/gcp/centos-79.yaml
  images/gcp/ubuntu-1804.yaml
  images/gcp/ubuntu-2004.yaml
  pkg/app/build_gcp.go
  pkg/app/config.go
  pkg/app/constants.go
  pkg/packer/manifests/gcp/packer.json.tmpl
Labels: fix
