Repository mesosphere/konvoy-image-builder, pull requests merged in 2022-01, with the labels that each got.

#196 docs: add dev docs for adding a new OS
  README.md
  docs/dev/README.md
  docs/dev/add-new-os.md
  docs/dev/nvidia-gpu.md
Labels: documentation, ignore-for-release

#200 feat: rhel82 FIPS
  Makefile
  overrides/fips.yaml
Labels: feature

#195 feat: convert centos 7 minimal iso to docker image
  Makefile
  ansible/roles/packages/tasks/install-redhat.yaml
  hack/base-images/README.md
  hack/base-images/centos-7-x86_64.ks
  hack/base-images/containerbuild.sh
  hack/os-packages/Makefile
  hack/os-packages/rpm-artifacts-getter-7/Dockerfile
  overrides/offline.yaml
Labels: feature

#202 fix: set the correct KIB version ami tag
  Makefile
  pkg/app/build.go
Labels: fix

#161 feat: gather images dynamically
  ansible/README.md
  ansible/_list-images.yaml
  ansible/global.yaml
  ansible/group_vars/all/defaults.yaml
  ansible/group_vars/all/images.yaml
  ansible/provision.yaml
  ansible/roles/config/handlers/main.yaml
  ansible/roles/config/tasks/main.yaml
  ansible/roles/config/templates/config.toml.tmpl
  ansible/roles/images/tasks/main.yaml
  ansible/roles/packages/tasks/config.yaml
  ansible/roles/packages/tasks/install-flatcar.yaml
  ansible/roles/version/tasks/main.yaml
  overrides/fips.yaml
  overrides/image-list.yaml
Labels: feature

#206 fix: Allow user to provide a subset of registry configuration fields
  ansible/roles/config/templates/config.toml.tmpl
Labels: fix

#205 chore: create RHEL 7.9 fips image for airgapped installations
  Makefile
  ansible/roles/packages/tasks/install-redhat.yaml
  hack/os-packages/Makefile
  hack/os-packages/rpm-artifacts-getter-7/Dockerfile
  hack/os-packages/rpm-artifacts-getter/centos/7/Dockerfile
  hack/os-packages/rpm-artifacts-getter/centos/7/containerd.repo
  hack/os-packages/rpm-artifacts-getter/centos/7/kubernetes.repo
  hack/os-packages/rpm-fips-artifacts-getter/centos/7/Dockerfile
  hack/os-packages/rpm-fips-artifacts-getter/centos/7/containerd.fips.repo
  hack/os-packages/rpm-fips-artifacts-getter/centos/7/kubernetes.fips.repo
  overrides/offline-fips.yaml
Labels: ignore-for-release

#211 fix(ansible): reuse roles for image saving
  Dockerfile.devkit
  Makefile
  ansible/_list-images.yaml
  ansible/list-images.yaml
  ansible/roles/images/tasks/main.yaml
  ansible/roles/packages/handlers/main.yaml
  ansible/roles/packages/tasks/config.yaml
  ansible/roles/packages/tasks/install-debian.yaml
  ansible/roles/packages/tasks/install-flatcar.yaml
  ansible/roles/packages/tasks/install-redhat.yaml
  ansible/roles/packages/tasks/install-suse.yaml
  ansible/roles/sysprep/tasks/main.yml
  ansible/roles/sysprep/tasks/redhat.yml
  hack/os-packages/Makefile
  overrides/image-list.yaml
Labels: fix

#208 feat: create RHEL 8.2 and RHEL 8.4 fips image for air-gapped installations
  Makefile
  ansible/roles/packages/tasks/install-redhat.yaml
  hack/os-packages/Makefile
  hack/os-packages/rpm-artifacts-getter/centos/7/fips/Dockerfile
  hack/os-packages/rpm-artifacts-getter/centos/7/fips/containerd.fips.repo
  hack/os-packages/rpm-artifacts-getter/centos/7/fips/kubernetes.fips.repo
  hack/os-packages/rpm-artifacts-getter/redhat/7/CentoOS-Linux-extra.repo
  hack/os-packages/rpm-artifacts-getter/redhat/7/Dockerfile
  hack/os-packages/rpm-artifacts-getter/redhat/7/containerd.repo
  hack/os-packages/rpm-artifacts-getter/redhat/7/fips/CentOS-Linux-BaseOS.repo
  hack/os-packages/rpm-artifacts-getter/redhat/7/fips/CentoOS-Linux-extra.repo
  hack/os-packages/rpm-artifacts-getter/redhat/7/fips/Dockerfile
  hack/os-packages/rpm-artifacts-getter/redhat/7/fips/containerd.fips.repo
  hack/os-packages/rpm-artifacts-getter/redhat/7/fips/kubernetes.fips.repo
  hack/os-packages/rpm-artifacts-getter/redhat/7/kubernetes.repo
  hack/os-packages/rpm-artifacts-getter/redhat/8/CentOS-Linux-AppStream.repo
  hack/os-packages/rpm-artifacts-getter/redhat/8/CentOS-Linux-BaseOS.repo
  hack/os-packages/rpm-artifacts-getter/redhat/8/Dockerfile
  hack/os-packages/rpm-artifacts-getter/redhat/8/containerd.repo
  hack/os-packages/rpm-artifacts-getter/redhat/8/fips/CentOS-Linux-AppStream.repo
  hack/os-packages/rpm-artifacts-getter/redhat/8/fips/CentOS-Linux-BaseOS.repo
  hack/os-packages/rpm-artifacts-getter/redhat/8/fips/Dockerfile
  hack/os-packages/rpm-artifacts-getter/redhat/8/fips/containerd.fips.repo
  hack/os-packages/rpm-artifacts-getter/redhat/8/fips/kubernetes.fips.repo
  hack/os-packages/rpm-artifacts-getter/redhat/8/kubernetes.repo
  overrides/offline-fips.yaml
  overrides/offline.yaml
Labels: feature

#215 fix: allows users to set kubernetes version through flag in build command
  cmd/konvoy-image/cmd/args.go
  docs/cli/konvoy-image_build.md
  docs/cli/konvoy-image_generate.md
  docs/cli/konvoy-image_provision.md
  pkg/app/build.go
  pkg/app/build_test.go
  pkg/app/errors.go
Labels: fix

#216 fix: add testify to go.mod
  go.mod
Labels: fix

#214 feat: adds an upload artifacts command to konvoy image builder
  .golangci.yml
  ansible/upload-artifacts.yaml
  cmd/konvoy-image/cmd/artifacts.go
  cmd/konvoy-image/cmd/root.go
  cmd/konvoy-image/cmd/upload.go
  cmd/konvoy-image/cmd/validate.go
  docs/cli/konvoy-image.md
  docs/cli/konvoy-image_upload.md
  docs/cli/konvoy-image_upload_artifacts.md
  pkg/app/artifacts.go
Labels: feature
