Repository mesosphere/konvoy-image-builder, pull requests merged in 2022-05, with the labels that each got.

#326 fix(azure): append build name to image sku
  pkg/app/build.go
  pkg/app/config.go
Labels: fix

#330 fix: adds a v1 to copy path
  Makefile
Labels: fix

#333 fix: README remove old test status
  README.md
Labels: fix

#336 fix: remove extra "release" keyword from vsphere template name
  images/ova/rhel-79.yaml
  images/ova/rhel-84.yaml
  pkg/packer/manifests/vsphere/packer.json.tmpl
Labels: fix

#338 feat(gpu): add image tags
  ansible/group_vars/all/defaults.yaml
  ansible/roles/gpu/defaults/main.yaml
  overrides/nvidia.yaml
  pkg/app/config.go
  pkg/app/config_test.go
  pkg/app/constants.go
  pkg/packer/manifests/aws/packer.json.tmpl
  pkg/packer/manifests/azure/packer.json.tmpl
  pkg/packer/manifests/vsphere/packer.json.tmpl
Labels: feature

#345 chore: Update vscode-go settings
  .vscode/settings.json
Labels: ignore-for-release

#327 feat(oracle): support installing RHCK kernel
  ansible/group_vars/all/defaults.yaml
  ansible/roles/packages/tasks/oracle.yaml
  ansible/roles/packages/tasks/redhat.yaml
  overrides/rhck.yaml
Labels: feature

#351 fix: set outputs from release please
  .github/workflows/release-main.yml
Labels: fix

#355 feat: dynamic containerd install per OS
  Dockerfile
  Dockerfile.devkit
  ansible/group_vars/all/defaults.yaml
  ansible/roles/containerd/tasks/install.yaml
  ansible/roles/offline/tasks/upload.yaml
  ansible/roles/offline/templates/linux_cat_os-release.yaml
  images/ami/centos-79.yaml
  images/azure/centos-79.yaml
  make/images.mk
Labels: feature

#344 [D2IQ-88880] feat: adding skeleton for gcp command to build images (hidden)
  cmd/konvoy-image/cmd/build.go
  cmd/konvoy-image/cmd/gcp.go
Labels: feature

#360 chore: all images to include point releases
  ansible/roles/repo/tasks/redhat.yaml
  ansible/roles/setup_versionlock/tasks/redhat.yaml
  images/ami/oracle-79.yaml
  images/ami/oracle-84.yaml
  images/azure/oracle-79.yaml
  images/azure/oracle-84.yaml
  images/azure/rhel-79.yaml
  images/azure/rhel-84.yaml
  make/images.mk
Labels: ignore-for-release

#361 fix: set token param correctly
  .github/workflows/release-main.yml
Labels: fix

#367 fix: correctly set default pause image
  ansible/roles/containerd/tasks/install.yaml
Labels: fix

#350 feat: create centos images for gcp
  Makefile
  README.md
  ansible/roles/providers/tasks/googlecompute.yml
  ansible/roles/providers/tasks/main.yml
  ansible/roles/providers/tasks/misc.yml
  cmd/konvoy-image/cmd/aws.go
  cmd/konvoy-image/cmd/azure.go
  cmd/konvoy-image/cmd/gcp.go
  docs/cli/konvoy-image_build.md
  docs/cli/konvoy-image_build_aws.md
  docs/cli/konvoy-image_build_azure.md
  docs/cli/konvoy-image_build_gcp.md
  docs/cli/konvoy-image_generate_aws.md
  docs/cli/konvoy-image_generate_azure.md
  docs/dev/nvidia-gpu.md
  go.mod
  go.sum
  images/gcp/centos-79.yaml
  pkg/app/build.go
  pkg/app/build_aws.go
  pkg/app/build_azure.go
  pkg/app/build_gcp.go
  pkg/app/config.go
  pkg/app/constants.go
  pkg/gcp/gcp.go
  pkg/packer/manifest.go
  pkg/packer/manifests/gcp/packer.json.tmpl
  pkg/packer/manifests/packer.go
Labels: feature
