Repository mesosphere/konvoy-image-builder, pull requests merged in 2022-07, with the labels that each got.

#401 feat: set a GCP image-family that can be used in dkp
  pkg/packer/manifests/gcp/packer.json.tmpl
Labels: feature

#409 fix: vSphere fixes
  cmd/konvoy-image-wrapper/cmd/wrapper.go
  images/ova/rhel-79.yaml
  images/ova/rhel-84.yaml
  test/infra/vsphere/packer-vsphere-airgap.yaml.tmpl
Labels: fix

#418 fix: gon release fixes
  .github/workflows/release-main.yml
  gon.hcl
Labels: fix

#423 fix: always use fix for CAPPP bumps
  .github/workflows/release-main.yml
Labels: fix

#427 fix: fix ref in release tag ci
  .github/workflows/release-tag.yaml
Labels: fix

#429 fix: use other user token that can run actions
  .github/workflows/release-main.yml
  .github/workflows/release-tag.yaml
Labels: fix

#430 chore(main): release 1.19.4
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#431 fix: various cleanups for release-tag action
  .github/workflows/release-tag.yaml
  .goreleaser.yml
Labels: fix

#433 fix: gon.hcl for binary signing
  gon.hcl
Labels: fix

#434 chore(main): release 1.19.6
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#435 fix: notarization and upload fixes
  .github/workflows/release-tag.yaml
  gon.hcl
Labels: fix

#436 chore(main): release 1.19.7
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending
