Repository mesosphere/konvoy-image-builder, pull requests merged in 2023-03, with the labels that each got.

#701 fix: fallback to ansible_user_id when using root user
  ansible/roles/sysprep/tasks/main.yml
Labels: fix, runs-e2e-tests

#703 ci: remove Rocky 9.1 FIPS builds
  .github/workflows/aws-e2e.yaml
  .github/workflows/release-ami.yaml
Labels: runs-e2e-tests

#704 fix: skip subscribing
  ansible/roles/repo/tasks/redhat.yaml
Labels: runs-e2e-tests

#702 chore(main): release 2.2.1
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending, runs-e2e-tests

#713 fix: set limitnofile
  .github/workflows/vsphere-e2e.yaml
  ansible/roles/containerd/tasks/main.yaml
  ansible/roles/containerd/templates/etc/systemd/system/containerd.service.d/max-files.conf
  ansible/roles/repo/tasks/redhat.yaml
  cmd/konvoy-image-wrapper/cmd/wrapper.go
  pkg/packer/manifests/vsphere/packer.pkr.hcl
Labels: fix, runs-e2e-tests

#712 chore(main): release 2.2.2
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#717 ci: adds conditions per provider
  .github/workflows/aws-e2e.yaml
  .github/workflows/azure-e2e.yaml
  .github/workflows/gcp-e2e.yaml
  .github/workflows/vsphere-e2e.yaml
Labels: runs-gcp-tests

#718 fix: set correct compute_gallery_image_id
  pkg/packer/manifests/azure/packer.pkr.hcl
Labels: fix

#719 chore(main): release 2.2.3
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#723 fix: allow building aws images using source_ami
  Makefile
  pkg/packer/manifests/aws/packer.pkr.hcl
Labels: fix, runs-aws-tests

#725 chore(main): release 2.2.4
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#735 fix: set image_version 9.1 for Rocky on Azure
  .github/workflows/azure-e2e.yaml
  .github/workflows/release-azure.yaml
  ansible/roles/providers/tasks/azure-redhat.yml
  images/azure/rocky-91.yaml
Labels: do not merge, fix, runs-azure-tests

#736 chore(main): release 2.2.5
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#739 fix: uses 80gb for all azure builds and removes extra
  ansible/roles/providers/tasks/azure-redhat.yml
  pkg/packer/manifests/azure/packer.pkr.hcl
Labels: fix, runs-azure-tests

#741 chore(main): release 2.2.6
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#738 feat: do not copy stdin and set tty to false
  cmd/konvoy-image-wrapper/cmd/wrapper.go
Labels: feature

#749 fix: Retry containerd yum/rpm tasks up to 30s
  ansible/roles/containerd/tasks/redhat.yaml
Labels: fix

#752 ci: update vsphere base template defaults
  hack/vsphere/main.tf
  images/ova/rhel-79.yaml
  images/ova/rhel-84.yaml
  images/ova/rhel-86.yaml
  images/ova/rocky-91.yaml
  images/ova/ubuntu-2004.yaml
Labels: runs-vsphere-tests

#756 fix: merge conflicts
  images/ova/rhel-79.yaml
  images/ova/rhel-84.yaml
Labels: fix

#748 Upgrade kubernetes version to 1.26.3
  ansible/group_vars/all/defaults.yaml
  images/common.yaml
Labels: runs-e2e-tests

#724 chore: remove unused HCL templating code
  pkg/app/build.go
  pkg/app/config.go
  pkg/packer/manifest.go
Labels: ignore-for-release, runs-e2e-tests

#765 fix: new oracle
  images/ami/oracle-79.yaml
Labels: fix

#766 fix: pin ansible collection versions
  Dockerfile
  Dockerfile.devkit
Labels: fix, runs-e2e-tests

#714 ci: execute all e2e tests on PR label with one GHA workflow
  .github/workflows/aws-e2e.yaml
  .github/workflows/azure-e2e.yaml
  .github/workflows/build-devkit-image.yaml
  .github/workflows/gcp-e2e.yaml
  .github/workflows/run-all-e2e-tests.yaml
  .github/workflows/vsphere-e2e.yaml
  Dockerfile.devkit
  Makefile
  README.md
Labels: runs-e2e-tests-temp
