Repository mesosphere/konvoy-image-builder, pull requests merged in 2023-06, with the labels that each got.

#815 chore(main): release 2.4.1
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#819 chore: remove deprecated vsphere base template implementations
  pkg/packer/manifests/vsphere/base/.env.sample
  pkg/packer/manifests/vsphere/base/README.md
  pkg/packer/manifests/vsphere/base/linux/centos/http/7/ks.cfg
  pkg/packer/manifests/vsphere/base/linux/centos/http/8/ks.cfg
  pkg/packer/manifests/vsphere/base/linux/rhel
  pkg/packer/manifests/vsphere/base/packer-base.json
  pkg/packer/manifests/vsphere/base/packer-ubuntu-base.json
  pkg/packer/manifests/vsphere/base/rhel-7.9-base.json
  pkg/packer/manifests/vsphere/base/rhel-8.4-base.json
  pkg/packer/manifests/vsphere/base/rhel-8.6-base.json
  pkg/packer/manifests/vsphere/base/run.sh
  pkg/packer/manifests/vsphere/base/ubuntu-2004-base.json
  pkg/packer/manifests/vsphere/base/vsphere-base.json
  pkg/packer/manifests/vsphere/packer.pkr.hcl
Labels: ignore-for-release, runs-vsphere-tests

#826 ci: use Flatcar LTS version in e2e tests
  images/ami/flatcar.yaml
Labels: runs-aws-tests

#828 fix: upgrade docker in flatcar 3033.3.x LTS for k8s 1.26 support
  .gitignore
  Makefile
  ansible/group_vars/all/defaults.yaml
  ansible/roles/containerd/files/3033.3.x-flatcar-lts/etc/systemd/system/containerd.service
  ansible/roles/containerd/files/3033.3.x-flatcar-lts/etc/systemd/system/docker.service
  ansible/roles/containerd/files/3033.3.x-flatcar-lts/etc/systemd/system/docker.socket
  ansible/roles/containerd/files/3033.3.x-flatcar-lts/etc/systemd/system/prepare-docker.service
  ansible/roles/containerd/tasks/install-flatcar.yaml
Labels: fix, runs-aws-tests

#829 fix: force update the offline repo metadata cache
  ansible/roles/repo/tasks/redhat-offline.yaml
Labels: fix, runs-aws-tests

#830 chore(main): release 2.4.2
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending, runs-gcp-tests, runs-aws-tests, runs-azure-tests

#835 chore: simplify installation of Goss plugin for packer
  Dockerfile
  Dockerfile.devkit
  pkg/packer/manifests/aws/packer.pkr.hcl
  pkg/packer/manifests/azure/packer.pkr.hcl
  pkg/packer/manifests/gcp/packer.pkr.hcl
  pkg/packer/manifests/vsphere/packer.pkr.hcl
Labels: ignore-for-release, runs-e2e-tests

#836 feat: Upgrade kubernetes version to v1.26.6 and CRI tools
  ansible/group_vars/all/defaults.yaml
  images/common.yaml
Labels: feature, ready, runs-vsphere-tests, runs-aws-tests

#840 chore(main): release 2.5.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#820 fix: missing resource_pool KIB 1.24
  .github/workflows/vsphere-e2e.yaml
  cmd/konvoy-image-wrapper/cmd/wrapper.go
  pkg/packer/manifests/vsphere/packer.json.tmpl
Labels: fix, runs-e2e-tests

#847 fix: backport CI changes in release-1.24
  .github/workflows/aws-e2e.yaml
  .github/workflows/azure-e2e.yaml
  .github/workflows/build.yml
  .github/workflows/conventional-label.yaml
  .github/workflows/gcp-e2e.yaml
  .github/workflows/lint.yml
  .github/workflows/release-ami.yaml
  .github/workflows/release-kib.yaml
  .github/workflows/release-main.yml
  .github/workflows/scorecards.yml
  .github/workflows/sync-cli-docs.yaml
  .github/workflows/vsphere-e2e.yaml
Labels: fix, runs-e2e-tests

#846 fix: backport CI changes in release-2.2
  .github/workflows/aws-e2e.yaml
  .github/workflows/azure-e2e.yaml
  .github/workflows/build.yml
  .github/workflows/conventional-label.yaml
  .github/workflows/gcp-e2e.yaml
  .github/workflows/lint.yml
  .github/workflows/next-release-version.yml
  .github/workflows/release-ami.yaml
  .github/workflows/release-azure.yaml
  .github/workflows/release-gcp-template.yaml
  .github/workflows/release-kib.yaml
  .github/workflows/release-vsphere-template.yaml
  .github/workflows/scorecards.yml
  .github/workflows/sync-cli-docs.yaml
  .github/workflows/unit-test.yml
  .github/workflows/vsphere-e2e.yaml
  .golangci.yml
Labels: fix, runs-e2e-tests

#842 chore: Trigger version updates in Confluence
  .github/workflows/confluence-docs.yaml
Labels: ignore-for-release, ready

#845 fix: install epel repo in RHEL 7 using static repo file (#781)
  ansible/roles/repo/defaults/main.yaml
  ansible/roles/repo/files/etc/yum.repos.d/epel-7.repo
  ansible/roles/repo/tasks/redhat.yaml
  images/common.yaml
Labels: fix, runs-e2e-tests, runs-aws-tests

#844 fix: install epel repo in RHEL 7 using static repo file (#781)
  ansible/roles/repo/defaults/main.yaml
  ansible/roles/repo/files/etc/yum.repos.d/epel-7.repo
  ansible/roles/repo/tasks/redhat.yaml
  images/common.yaml
Labels: fix, runs-e2e-tests, runs-aws-tests

#843 fix: install epel repo in RHEL 7 using static repo file (#781)
  ansible/roles/repo/defaults/main.yaml
  ansible/roles/repo/files/etc/yum.repos.d/epel-7.repo
  ansible/roles/repo/tasks/redhat.yaml
  images/common.yaml
Labels: fix, runs-e2e-tests, runs-aws-tests
