Repository mesosphere/konvoy-image-builder, pull requests merged in 2023-10, with the labels that each got.

#928 fix: downgrade vsphere version
  test/infra/vsphere/main.tf
Labels: fix, runs-vsphere-tests

#923 feat: upgrade Kubernetes to 1.27.6
  ansible/group_vars/all/defaults.yaml
  images/common.yaml
Labels: feature, runs-e2e-tests

#908 chore(main): release 2.8.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending, runs-e2e-tests

#938 fix: downgrade cloud-init package for ubuntu OS
  ansible/roles/packages/tasks/debian.yaml
Labels: fix

#942 fix: downgrade cloud-init to 23.1.2-0ubuntu0~20.04.2
  ansible/roles/packages/tasks/debian.yaml
Labels: fix

#941 chore(main): release 2.8.2
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending, runs-aws-tests

#943 fix: install pinned cloud-init for only ubuntu 20.04
  ansible/group_vars/all/defaults.yaml
  ansible/roles/packages/tasks/debian.yaml
  images/ami/ubuntu-2004.yaml
Labels: fix, runs-aws-tests

#944 chore(main): release 2.8.3
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#945 fix: install pinned cloud-init for only ubuntu 20.04
  ansible/group_vars/all/defaults.yaml
  ansible/roles/packages/tasks/debian.yaml
  images/ami/ubuntu-2004.yaml
Labels: fix, runs-aws-tests
