Repository mesosphere/konvoy-image-builder, pull requests merged in 2023-02, with the labels that each got.

#647 fix: configure containerd runc plugin for nvidia
  ansible/roles/config/templates/config.toml.tmpl
Labels: fix

#649 feat: build vsphere template for rockylinux 9.1
  ansible/roles/providers/tasks/vmware.yml
  ansible/roles/sysprep/tasks/redhat.yml
  images/ova/rocky-91.yaml
  make/ci.mk
  make/images.mk
  pkg/packer/manifests/vsphere/packer.pkr.hcl
Labels: feature

#616 chore(main): release 2.0.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#656 feat: add images file for ubuntu 20.04
  images/ova/ubuntu-2004.yaml
Labels: feature

#665 fix: build rocky linux 9.0 azure image
  .github/workflows/azure-e2e.yaml
  images/azure/rocky-90.yaml
  magefile.go
Labels: fix, runs-e2e-tests

#664 ci: adds gcp tests
  .github/workflows/gcp-e2e.yaml
  magefile.go
Labels: runs-e2e-tests

#660 chore(main): release 2.0.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#668 ci: remove make directory
  Makefile
  make/ci.mk
  make/images.mk
Labels: runs-e2e-tests

#676 fix: epel repos not working with some RHEL images
  ansible/roles/repo/tasks/redhat.yaml
Labels: fix, runs-e2e-tests

#678 feat: update Containerd to 1.6.17
  ansible/group_vars/all/defaults.yaml
Labels: feature, runs-e2e-tests

#675 fix: use subscription manager to get kernel headers
  .github/workflows/aws-e2e.yaml
  ansible/group_vars/all/system.yaml
  ansible/provision.yaml
  ansible/roles/gpu/tasks/nvidia-gpu-RHEL.yaml
  ansible/roles/repo/tasks/redhat.yaml
  ansible/roles/sysprep/tasks/redhat.yml
Labels: fix

#682 fix: netwmanager config for OracleLinux 7
  ansible/roles/sysprep/tasks/redhat.yml
Labels: fix, runs-e2e-tests

#681 chore(main): release 2.1.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending, runs-e2e-tests

#690 fix: Use always section instead of rescue to remove RHEL subscription
  ansible/provision.yaml
Labels: fix, runs-e2e-tests

#693 ci: Fail workflow run if any job fails
  .github/workflows/aws-e2e.yaml
  .github/workflows/azure-e2e.yaml
  .github/workflows/gcp-e2e.yaml
  .github/workflows/release-ami.yaml
  .github/workflows/release-azure.yaml
  .github/workflows/release-gcp-template.yaml
  .github/workflows/release-vsphere-template.yaml
  .github/workflows/vsphere-e2e.yaml
Labels: runs-e2e-tests

#692 fix: set force = true and update k8s http source
  ansible/group_vars/all/defaults.yaml
  ansible/provision.yaml
  ansible/roles/containerd/tasks/install.yaml
  ansible/roles/gpu/tasks/nvidia-gpu.yaml
  ansible/roles/kubeadm/tasks/flatcar.yaml
  ansible/roles/packages/tasks/crictl-url.yaml
  ansible/roles/packages/tasks/url.yaml
  ansible/roles/providers/tasks/googlecompute.yml
  ansible/roles/setup_versionlock/tasks/redhat.yaml
Labels: fix

#694 fix: set force = true and update k8s http source
  ansible/group_vars/all/defaults.yaml
  ansible/roles/containerd/tasks/install.yaml
  ansible/roles/gpu/tasks/nvidia-gpu.yaml
  ansible/roles/kubeadm/tasks/flatcar.yaml
  ansible/roles/packages/tasks/crictl-url.yaml
  ansible/roles/packages/tasks/url.yaml
  ansible/roles/providers/tasks/googlecompute.yml
  ansible/roles/setup_versionlock/tasks/redhat.yaml
Labels: fix, runs-e2e-tests

#684 feat: Install only required ansible collections
  Dockerfile
  Dockerfile.devkit
  ansible/requirements.txt
  ansible/roles/offline/tasks/upload.yaml
  docs/dev/ansible-modules.md
  requirements.txt
Labels: feature, ready, runs-e2e-tests

#691 chore(main): release 2.2.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending
