Repository mesosphere/konvoy-image-builder, pull requests merged in 2023-12, with the labels that each got.

#968 fix: Add directives to false positives reported by goleaks linter
  cmd/konvoy-image-wrapper/cmd/wrapper.go
  pkg/app/config.go
Labels: fix

#967 fix: Install gcloud CLI system package
  ansible/roles/providers/tasks/googlecompute.yml
  images/gcp/centos-79.yaml
  images/gcp/ubuntu-1804.yaml
  images/gcp/ubuntu-2004.yaml
Labels: fix, runs-gcp-tests

#971 [release-2.5] fix: Add directives to false positives reported by goleaks linter
  cmd/konvoy-image-wrapper/cmd/wrapper.go
  pkg/app/config.go
Labels: fix

#972 [release-2.5] fix: Install gcloud CLI system package
  ansible/roles/providers/tasks/googlecompute.yml
  images/gcp/centos-79.yaml
  images/gcp/ubuntu-1804.yaml
  images/gcp/ubuntu-2004.yaml
Labels: fix, runs-gcp-tests

#969 chore(main): release 2.8.4
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#966 fix: bumps sles to sp5
  images/ami/sles-15.yaml
Labels: fix, runs-aws-tests

#973 chore(main): release 2.8.5
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending
