Repository mesosphere/konvoy-image-builder, pull requests merged in 2023-04, with the labels that each got.

#750 chore(main): release 2.3.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending, runs-e2e-tests

#782 fix: install epel repo in RHEL 7 using static repo file
  ansible/roles/repo/defaults/main.yaml
  ansible/roles/repo/files/etc/yum.repos.d/epel-7.repo
  ansible/roles/repo/tasks/redhat.yaml
  images/common.yaml
Labels: runs-aws-tests

#781 fix: install epel repo in RHEL 7 using static repo file
  ansible/roles/repo/defaults/main.yaml
  ansible/roles/repo/files/etc/yum.repos.d/epel-7.repo
  ansible/roles/repo/tasks/redhat.yaml
  images/common.yaml
Labels: fix

#786 fix: set SSH_PRIVATE_KEY_FILE env variable for docker wrapper
  cmd/konvoy-image-wrapper/cmd/wrapper.go
Labels: fix
