Repository mesosphere/konvoy-image-builder, pull requests merged in 2023-01, with the labels that each got.

#611 fix: retag coredns image with k8s.gcr.io/coredns
  ansible/roles/images/tasks/check-or-pull-images.yaml
Labels: fix

#626 fix: use new oracle 7.9 ami
  images/ami/oracle-79.yaml
Labels: fix

#628 fix: use --force when retagging CoreDNS image
  ansible/roles/images/tasks/check-or-pull-images.yaml
Labels: fix

#631 feat: Install specific cri-tools package on debian derivatives
  ansible/group_vars/all/defaults.yaml
  ansible/roles/kubeadm/tasks/debian.yaml
Labels: feature, needs-backport

#640 fix: use new centos 7.9 base AMI (#573)
  images/ami/centos-7.yaml
Labels: fix

#643 [release-1.24] feat: Use cri-tools v1.25.0 for Debian derivatives
  ansible/group_vars/all/defaults.yaml
  ansible/roles/kubeadm/tasks/debian.yaml
  ansible/roles/packages/tasks/flatcar.yaml
Labels: feature

#642 [release-1.19] feat: Use cri-tools v1.25.0 for Debian derivatives
  ansible/group_vars/all/defaults.yaml
  ansible/roles/kubeadm/tasks/debian.yaml
  ansible/roles/packages/tasks/flatcar.yaml
Labels: feature

#636 [release-1.17] feat: Use cri-tools v1.23.0 on debian derivatives
  ansible/group_vars/all/defaults.yaml
  ansible/roles/kubeadm/tasks/debian.yaml
  ansible/roles/packages/tasks/flatcar.yaml
Labels: ready

#635 [release-1.5] feat: Use cri-tools v1.23.0 for Debian derivatives
  ansible/group_vars/all/defaults.yaml
  ansible/roles/packages/tasks/install-debian.yaml
  ansible/roles/packages/tasks/install-flatcar.yaml
Labels: feature, ready

#644 fix: configure containerd runc plugin for nvidia
  ansible/roles/config/templates/config.toml.tmpl
Labels: fix

#637 feat: build rocky linux 9.1 images
  .github/workflows/aws-e2e.yaml
  ansible/roles/containerd/tasks/redhat.yaml
  ansible/roles/kubeadm/tasks/redhat.yaml
  ansible/roles/packages/tasks/redhat.yaml
  ansible/roles/setup_versionlock/tasks/redhat.yaml
  goss/rocky
  goss/rockylinux-9
  images/ami/rocky-91.yaml
  images/azure/rocky-91.yaml
  magefile.go
  make/ci.mk
  make/images.mk
  pkg/packer/manifests/azure/packer.pkr.hcl
Labels: feature

#627 feat: support building Ubuntu 20.04 with offline OS packages bundle
  ansible/roles/containerd/tasks/debian.yaml
  ansible/roles/kubeadm/tasks/debian.yaml
  ansible/roles/packages/tasks/debian.yaml
  ansible/roles/repo/tasks/debian-offline.yaml
  ansible/roles/repo/tasks/main.yaml
  ansible/roles/repo/tasks/redhat-offline.yaml
  ansible/roles/repo/templates/rpm-offline.repo
  ansible/roles/sysprep/tasks/debian.yml
Labels: feature
