Repository mesosphere/konvoy-image-builder, pull requests merged in 2023-08, with the labels that each got.

#866 fix: aws cli issue flatcar
  ansible/roles/providers/tasks/aws.yml
Labels: fix, runs-aws-tests

#873 [release-2.2] build: fix pip build error
  requirements-devkit.txt
Labels: runs-gcp-tests

#874 [release-2.2] chore: update gitignore for vsphere-bastion.pub
  .gitignore
Labels: ignore-for-release

#884 chore: Remove docs trigger
  .github/workflows/confluence-docs.yaml
Labels: ignore-for-release, ready

#865 chore(main): release 2.6.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#885 chore: git ignore vsphere-bastion.pub
  .gitignore
Labels: ignore-for-release

#886 fix: start usr-libexec.mount to also support pre-provisioned
  ansible/roles/packages/tasks/flatcar.yaml
Labels: fix, runs-vsphere-tests

#887 chore(main): release 2.6.1
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#889 fix: force redownload of Kubelet and kubectl binaries for Flatcar
  ansible/roles/packages/tasks/url.yaml
Labels: fix, needs-backport, runs-aws-tests

#890 fix: don't override Docker systemd unit file for Flatcar
  ansible/roles/containerd/tasks/install-flatcar.yaml
Labels: fix, needs-backport, runs-aws-tests

#891 chore(main): release 2.6.2
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending
