Repository mesosphere/konvoy-image-builder, pull requests merged in 2023-05, with the labels that each got.

#784 chore(main): release 2.3.1
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#788 fix: remove packer directory from goreleaser configuration
  .goreleaser.yml
Labels: fix

#798 fix: backport mindthegap bump to release-2.2
  Dockerfile.devkit
Labels: fix, runs-e2e-tests, runs-aws-tests

#801 Faiq/kib podman
  .github/workflows/podman-aws-e2e.yaml
  .github/workflows/run-all-e2e-tests.yaml
  Dockerfile
  Makefile
  cmd/konvoy-image-wrapper/cmd/wrapper.go
Labels: runs-e2e-tests, runs-aws-tests

#808 fix: adds missing package to address sles issue
  ansible/roles/containerd/tasks/suse.yaml
Labels: fix, runs-e2e-tests

#807 fix: adds apparmor abstractions
  ansible/roles/containerd/tasks/suse.yaml
Labels: fix

#805 ci: changed runner labels
  .github/workflows/aws-e2e.yaml
  .github/workflows/azure-e2e.yaml
  .github/workflows/build-devkit-image.yaml
  .github/workflows/build.yml
  .github/workflows/conventional-label.yaml
  .github/workflows/gcp-e2e.yaml
  .github/workflows/lint.yml
  .github/workflows/next-release-version.yml
  .github/workflows/release-ami.yaml
  .github/workflows/release-azure.yaml
  .github/workflows/release-gcp-template.yaml
  .github/workflows/release-kib.yaml
  .github/workflows/release-vsphere-template.yaml
  .github/workflows/scorecards.yml
  .github/workflows/sync-cli-docs.yaml
  .github/workflows/unit-test.yml
  .github/workflows/vsphere-e2e.yaml
Labels: runs-e2e-tests

#789 feat: podman as a supported container engine in konvoy image builder
  .github/workflows/podman-aws-e2e.yaml
  .github/workflows/run-all-e2e-tests.yaml
  Dockerfile
  Makefile
  cmd/konvoy-image-wrapper/cmd/wrapper.go
  cmd/konvoy-image-wrapper/image/common.go
  cmd/konvoy-image-wrapper/image/image.go
  cmd/konvoy-image-wrapper/image/image_not_embedded.go
Labels: feature, runs-vsphere-tests, runs-aws-tests

#790 chore(main): release 2.4.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#809 feat: podman as a supported container engine
  .github/workflows/podman-aws-e2e.yaml
  .goreleaser.yml
  Dockerfile
  Makefile
  cmd/konvoy-image-wrapper/cmd/wrapper.go
  cmd/konvoy-image-wrapper/image/common.go
  cmd/konvoy-image-wrapper/image/image.go
  cmd/konvoy-image-wrapper/image/image_not_embedded.go
Labels: feature, runs-aws-tests

#814 fix: setting fs.may_detach_mounts for Oracle with RHCK kernel
  .github/workflows/aws-e2e.yaml
  ansible/roles/packages/meta/main.yaml
  ansible/roles/packages/tasks/redhat.yaml
  ansible/roles/rhck_kernel/tasks/main.yaml
  ansible/roles/rhck_kernel/tasks/oracle.yaml
  magefile.go
Labels: fix, runs-aws-tests
