Repository mesosphere/konvoy-image-builder, pull requests merged in 2023-09, with the labels that each got.

#898 build: Flatcar AMI
  .github/workflows/release-ami.yaml
  images/ami/flatcar.yaml
Labels: runs-aws-tests

#900 chore(main): release 2.7.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#901 fix: bump alpine from 3.15.4 to 3.15.6
  Dockerfile
  Dockerfile.devkit
  cmd/konvoy-image-wrapper/cmd/wrapper.go
  images/ova/rhel-79.yaml
  images/ova/rhel-84.yaml
  images/ova/rhel-86.yaml
  images/ova/rocky-91.yaml
  images/ova/ubuntu-2004.yaml
  pkg/packer/manifests/vsphere/packer.pkr.hcl
  test/infra/vsphere/packer-vsphere-airgap.yaml.tmpl
  test/infra/vsphere/variables.tf
Labels: runs-vsphere-tests

#905 fix: remove deprecated cmdline argument
  ansible/roles/config/templates/kubelet-drop-in.conf
Labels: fix, runs-e2e-tests

#906 chore(main): release 2.7.1
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#907 fix: RHEL 8.8 distribution_version
  images/ova/rhel-88.yaml
Labels: fix

#910 fix: RHEL 8.8 build_name
  images/ova/rhel-88.yaml
Labels: fix

#911 fix: bump alpine from 3.15.4 to 3.15.6 to patch zlib CVE
  Dockerfile
Labels: fix

#914 fix: use d2iq base templates
  test/infra/vsphere/variables.tf
Labels: fix, runs-vsphere-tests

#912 chore: download pip packages from downloads.d2iq.com
  magefile.go
Labels: ignore-for-release, runs-e2e-tests

#913 fix: bump alpine from 3.15.4 to 3.15.6 to patch zlib CVE
  Dockerfile
Labels: fix, runs-vsphere-tests
