Repository mesosphere/konvoy-image-builder, pull requests merged in 2024-08, with the labels that each got.

#1137 chore: bump go version
  go.mod
  go.sum
Labels: ignore-for-release, ready

#1133 feat: allows setting EUS repos with a flag
  bundles/redhat8.6/bundle.sh.gotmpl
  bundles/redhat8.6/packages.txt.gotmpl
  bundles/redhat8.8/bundle.sh.gotmpl
  bundles/redhat8.8/packages.txt.gotmpl
  cmd/konvoy-image-wrapper/cmd/create-package-bundle.go
  magefile.go
Labels: feature, runs-aws-tests

#1138 chore(main): release 2.11.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#1139 fix: adds ssm from docker image
  Dockerfile
  Dockerfile.devkit
  ansible/roles/providers/tasks/aws.yml
  bundles/redhat8.6/bundle.sh.gotmpl
  bundles/redhat8.8/bundle.sh.gotmpl
  bundles/rocky9.1/bundle.sh.gotmpl
Labels: fix, runs-aws-tests

#1141 chore(main): release 2.11.1
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#1144 feat: bumps cni to 1.3.0
  ansible/group_vars/all/defaults.yaml
Labels: feature

#1145 chore(main): release 2.12.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#1140 feat: embed k8s rpms in container
  Dockerfile
  Dockerfile.devkit
  ansible/roles/kubeadm/tasks/redhat.yaml
  ansible/roles/packages/tasks/redhat.yaml
  bundles/redhat8.6/bundle.sh.gotmpl
  bundles/redhat8.6/packages.txt.gotmpl
  bundles/redhat8.8/bundle.sh.gotmpl
  bundles/redhat8.8/packages.txt.gotmpl
  bundles/rocky9.1/bundle.sh.gotmpl
  bundles/rocky9.1/packages.txt.gotmpl
  bundles/ubuntu20.04/bundle.sh.gotmpl
  cmd/konvoy-image-wrapper/cmd/create-package-bundle.go
Labels: feature, runs-aws-tests

#1147 fix: removes duplicate key
  ansible/roles/packages/tasks/redhat.yaml
Labels: fix

#1148 fix: set sysctl settings for fs.inotify
  ansible/group_vars/all/defaults.yaml
  ansible/roles/providers/tasks/misc.yml
Labels: fix, runs-aws-tests

#1146 chore(main): release 2.13.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#1150 fix: cloud init problems with ubuntu
  .github/workflows/release-vsphere-template.yaml
  .github/workflows/vsphere-e2e.yaml
  ansible/roles/providers/tasks/main.yml
  ansible/roles/providers/tasks/vmware-redhat.yaml
  ansible/roles/providers/tasks/vmware.yml
  magefile.go
  test/infra/Makefile
  test/infra/vsphere/packer-vsphere-basic.yaml.tmpl
Labels: fix, runs-vsphere-tests

#1157 chore(main): release 2.13.1
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#1158 fix: cloud init problems with ubuntu (#1150)
  .github/workflows/release-vsphere-template.yaml
  .github/workflows/vsphere-e2e.yaml
  ansible/roles/providers/tasks/main.yml
  ansible/roles/providers/tasks/vmware-redhat.yaml
  ansible/roles/providers/tasks/vmware.yml
  magefile.go
  test/infra/Makefile
  test/infra/vsphere/packer-vsphere-basic.yaml.tmpl
Labels: fix, runs-vsphere-tests

#1159 fix: add macos binary notarization
  .github/workflows/release-kib.yaml
  .goreleaser-podman-e2e.yml
  .goreleaser.yml
Labels: fix

#1160 chore(main): release 2.13.2
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending
