Repository mesosphere/konvoy-image-builder, pull requests merged in 2024-10, with the labels that each got.

#1190 feat: add Oracle Linux 9.4 vSphere build configuration
  .github/workflows/release-vsphere-template.yaml
  .github/workflows/vsphere-e2e.yaml
  images/ova/oracle-94.yaml
  magefile.go
Labels: feature, runs-vsphere-tests

#1195 fix: update kubernetes version to 1.29.9
  Makefile
  ansible/group_vars/all/defaults.yaml
  images/common.yaml
Labels: runs-e2e-tests

#1197 fix(release-2.14): update kubernetes version to 1.29.9 (#1195)
  Makefile
  ansible/group_vars/all/defaults.yaml
  images/common.yaml
Labels: fix, runs-aws-tests

#1198 [release-2.8] fix: cloud init problems with ubuntu (#1150)
  ansible/roles/providers/tasks/main.yml
  ansible/roles/providers/tasks/vmware-redhat.yaml
  ansible/roles/providers/tasks/vmware.yml
Labels: runs-vsphere-tests

#1199 fix(release-2.9): remove using undefined flags in magefile
  bundles/redhat8.4/repo-templates/centos.repo
  magefile.go
Labels: runs-e2e-tests

#1200 [release-2.8] fix: bumps nvidia version to a newer one that no longer uses GPL symbols
  ansible/group_vars/all/defaults.yaml
Labels: fix, runs-aws-tests

#1201 [release-2.9] fix: bumps nvidia version to a newer one that no longer uses GPL symbols
  ansible/group_vars/all/defaults.yaml
Labels: fix, runs-aws-tests

#1202 fix: remove appstream code as its not needed
  ansible/group_vars/all/system.yaml
  ansible/roles/gpu/tasks/nvidia-gpu-RHEL.yaml
  ansible/roles/repo/tasks/redhat.yaml
Labels: fix, runs-aws-tests

#1203 fix: Allow open-vm-tools to wait indefinitely for cloud-init to finish
  ansible/roles/providers/files/etc/vmware-tools/tools.conf
Labels: fix, runs-vsphere-tests

#1206 build: update Go builder version to v1.19.13
  Dockerfile.devkit
Labels: runs-aws-tests

#1193 chore(main): release 2.16.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#1208 fix: update goss Packer plugin
  Dockerfile.devkit
  pkg/packer/manifests/aws/packer.pkr.hcl
  pkg/packer/manifests/azure/packer.pkr.hcl
  pkg/packer/manifests/gcp/packer.pkr.hcl
  pkg/packer/manifests/vsphere/packer.pkr.hcl
Labels: fix, runs-aws-tests

#1209 chore(main): release 2.16.1
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#1211 fix: tests for podman
  .github/workflows/podman-aws-e2e.yaml
Labels: runs-aws-tests

#1213 [release-2.9] fix: hack to load modulemd-tools for rhel 84
  bundles/redhat8.4/bundle.sh.gotmpl
  bundles/redhat8.4/repo-templates/rocky.repo
Labels: fix, runs-vsphere-tests

#1210 feat: adds rhel 8.10 support for aws
  .github/workflows/aws-e2e.yaml
  .github/workflows/release-ami.yaml
  ansible/roles/gpu/tasks/nvidia-gpu.yaml
  ansible/roles/repo/tasks/redhat.yaml
  bundles/redhat8.10/bundle.sh.gotmpl
  bundles/redhat8.10/packages.txt.gotmpl
  bundles/redhat8.10/repo-templates/kubernetes.repo.gotmpl
  cmd/konvoy-image-wrapper/cmd/create-package-bundle.go
  images/ami/rhel-810.yaml
  magefile.go
Labels: feature, runs-aws-tests

#1216 feat: adds rhel 8.10 vsphere support
  .github/workflows/release-vsphere-template.yaml
  .github/workflows/vsphere-e2e.yaml
  images/ova/rhel-810.yaml
Labels: feature, runs-vsphere-tests

#1215 fix: Replaces Azure rocky-9.1 with rocky-9.3 image
  .github/workflows/azure-e2e.yaml
  .github/workflows/release-azure.yaml
  ansible/roles/providers/tasks/azure-redhat.yml
  goss/rockylinux-x86_64
  images/azure/rocky-91.yaml
  images/azure/rocky-93.yaml
  magefile.go
Labels: fix, runs-azure-tests

#1212 chore(main): release 2.17.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#1217 fix: use Rocky 9 without a minor version for Azure
  .github/workflows/azure-e2e.yaml
  .github/workflows/release-azure.yaml
  images/azure/rocky-9.yaml
  magefile.go
Labels: fix, runs-azure-tests

#1218 chore(main): release 2.17.1
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending
