Repository mesosphere/konvoy-image-builder, pull requests merged in 2024-07, with the labels that each got.

#1116 fix: Make image load compatible with podman 4.x
  .github/workflows/podman-aws-e2e.yaml
  cmd/konvoy-image-wrapper/image/image.go
Labels: fix, runs-e2e-tests

#1117 fix: Make image load compatible with podman 4.x
  .github/workflows/podman-aws-e2e.yaml
  cmd/konvoy-image-wrapper/image/image.go
Labels: fix

#1118 fix: Make image load compatible with podman
  .github/workflows/podman-aws-e2e.yaml
  cmd/konvoy-image-wrapper/image/image.go
Labels: fix

#1119 fix: redhat 8.6 and redhat 8.8 gpu support
  bundles/redhat8.6/packages.txt.gotmpl
  bundles/redhat8.8/bundle.sh.gotmpl
  bundles/redhat8.8/packages.txt.gotmpl
Labels: fix, runs-aws-tests

#1120 fix: adds oracle 7 repos
  ansible/roles/containerd/tasks/redhat.yaml
  ansible/roles/repo/files/etc/yum.repos.d/epel-7.repo
Labels: fix, runs-aws-tests

#1122 fix: adds base os repo and kernel package
  bundles/redhat8.8/bundle.sh.gotmpl
  bundles/redhat8.8/packages.txt.gotmpl
Labels: fix, runs-e2e-tests

#1124 fix: remove snapshot groups
  pkg/packer/manifests/aws/packer.pkr.hcl
Labels: fix

#1123 chore(main): release 2.10.4
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#1126 fix: downgrade packer version
  Dockerfile.devkit
Labels: fix, runs-e2e-tests

#1127 chore(main): release 2.10.5
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending
