Repository mesosphere/konvoy-image-builder, pull requests merged in 2024-03, with the labels that each got.

#1028 fix: Configure yum to return an error on missing package
  bundles/centos7.9/bundle.sh.gotmpl
  bundles/redhat8.4/bundle.sh.gotmpl
  bundles/redhat8.6/bundle.sh.gotmpl
  bundles/redhat8.8/bundle.sh.gotmpl
  bundles/rocky9.1/bundle.sh.gotmpl
Labels: fix

#1027 [release-2.8][backport] fix: Update k8s debian package repositories to pkgs.k8s.io
  ansible/group_vars/all/defaults.yaml
  ansible/group_vars/all/system.yaml
  ansible/roles/repo/tasks/debian.yaml
Labels: runs-e2e-tests

#1030 [release-2.8][backport] feat: Update kubernetes version to v1.27.11
  ansible/group_vars/all/defaults.yaml
  images/common.yaml
Labels: runs-aws-tests

#1029 [release-2.8][backport] feat: update Containerd to 1.6.28
  ansible/group_vars/all/defaults.yaml
Labels: runs-aws-tests

#1026 feat: Create bundle for RHEL 7.9
  bundles/redhat7.9/bundle.sh.gotmpl
  bundles/redhat7.9/packages.txt.gotmpl
  bundles/redhat7.9/repo-templates/kubernetes.repo.gotmpl
  cmd/konvoy-image-wrapper/cmd/create-package-bundle.go
Labels: feature, runs-aws-tests

#1016 feat: create-package-bundle command to create OS package bundles for airgapped builds
  .github/workflows/aws-e2e.yaml
  .gitignore
  .goreleaser.yml
  bundles/centos7.9/bundle.sh.gotmpl
  bundles/centos7.9/packages.txt.gotmpl
  bundles/centos7.9/repo-templates/kubernetes.repo.gotmpl
  bundles/redhat7.9/bundle.sh.gotmpl
  bundles/redhat7.9/packages.txt.gotmpl
  bundles/redhat7.9/repo-templates/kubernetes.repo.gotmpl
  bundles/redhat8.4/bundle.sh.gotmpl
  bundles/redhat8.4/packages.txt.gotmpl
  bundles/redhat8.4/repo-templates/centos.repo
  bundles/redhat8.4/repo-templates/kubernetes.repo.gotmpl
  bundles/redhat8.6/bundle.sh.gotmpl
  bundles/redhat8.6/packages.txt.gotmpl
  bundles/redhat8.6/repo-templates/kubernetes.repo.gotmpl
  bundles/redhat8.8/bundle.sh.gotmpl
  bundles/redhat8.8/packages.txt.gotmpl
  bundles/redhat8.8/repo-templates/kubernetes.repo.gotmpl
  bundles/rocky9.1/bundle.sh.gotmpl
  bundles/rocky9.1/packages.txt.gotmpl
  bundles/rocky9.1/repo-templates/kubernetes.repo.gotmpl
  bundles/ubuntu20.04/bundle.sh.gotmpl
  bundles/ubuntu20.04/packages.txt.gotmpl
  cmd/konvoy-image-wrapper/cmd/create-package-bundle.go
  cmd/konvoy-image-wrapper/cmd/wrapper.go
  cmd/konvoy-image-wrapper/cmd/wrapper_test.go
  cmd/konvoy-image/cmd/artifacts.go
  cmd/konvoy-image/cmd/aws.go
  cmd/konvoy-image/cmd/azure.go
  cmd/konvoy-image/cmd/build.go
  cmd/konvoy-image/cmd/create-package-bundle.go
  cmd/konvoy-image/cmd/gcp.go
  cmd/konvoy-image/cmd/generate-docs.go
  cmd/konvoy-image/cmd/generate.go
  cmd/konvoy-image/cmd/provision.go
  cmd/konvoy-image/cmd/root.go
  cmd/konvoy-image/cmd/validate.go
  cmd/konvoy-image/cmd/vsphere.go
  docs/cli/konvoy-image.md
  docs/cli/konvoy-image_create-package-bundle.md
  go.mod
  go.sum
  magefile.go
  overrides/offline-fips.yaml
  overrides/offline.yaml
  test/e2e/ansible/app_test.go
  test/e2e/ansible/suite_test.go
Labels: feature

#1022 chore(main): release 2.9.1
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#1032 fix: kib release
  .github/workflows/release-kib.yaml
Labels: fix

#1033 chore(main): release 2.9.2
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#1031 [release-2.2] fix: ubuntu builds
  ansible/group_vars/all/defaults.yaml
  ansible/group_vars/all/system.yaml
  ansible/roles/packages/tasks/debian.yaml
  ansible/roles/repo/tasks/debian.yaml
  images/ami/ubuntu-2004.yaml
Labels: runs-aws-tests

#1034 fix: release tooling
  .github/workflows/release-kib.yaml
Labels: fix

#1035 chore(main): release 2.9.3
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#1042 fix: include python2-pip package for RHEL
  bundles/redhat8.4/packages.txt.gotmpl
  bundles/redhat8.6/packages.txt.gotmpl
  bundles/redhat8.8/packages.txt.gotmpl
  bundles/rocky9.1/packages.txt.gotmpl
Labels: fix

#1043 chore(main): release 2.9.5
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#1044 fix: release workflow
  .github/workflows/release-kib.yaml
Labels: fix

#1047 fix: adds an ubuntu release for kommander tests
  .github/workflows/release-ami.yaml
Labels: fix

#1048 fix: attempts to fix the bump again
  .github/workflows/release-kib.yaml
  hack/version-diff.sh
Labels: fix
