Repository mesosphere/konvoy-image-builder, pull requests merged in 2024-09, with the labels that each got.

#1165 feat: oracle 8.9 support
  .github/workflows/aws-e2e.yaml
  .github/workflows/release-ami.yaml
  ansible/roles/repo/files/etc/yum.repos.d/epel-7.repo
  ansible/roles/repo/tasks/redhat.yaml
  ansible/roles/rhck_kernel/tasks/oracle.yaml
  images/ami/oracle-89.yaml
  magefile.go
Labels: feature, runs-aws-tests

#1173 [release-2.5] fix: cloud init problems with ubuntu (#1158)
  ansible/roles/providers/tasks/main.yml
  ansible/roles/providers/tasks/vmware-redhat.yaml
  ansible/roles/providers/tasks/vmware.yml
Labels: fix

#1177 fix: Wait for concurrent apt process to release lock
  ansible/roles/packages/tasks/debian.yaml
  ansible/roles/sysprep/tasks/debian.yml
Labels: fix, needs-backport, runs-vsphere-tests

#1170 feat: Support creating Ubuntu 22.04 OVA (vSphere) image
  .github/workflows/release-vsphere-template.yaml
  .github/workflows/vsphere-e2e.yaml
  images/ova/ubuntu-2204.yaml
  magefile.go
Labels: needs-backport, runs-vsphere-tests

#1179 [release-2.9] fix: Wait for concurrent apt process to release lock
  ansible/roles/packages/tasks/debian.yaml
  ansible/roles/sysprep/tasks/debian.yml
Labels: runs-aws-tests

#1169 chore(main): release 2.14.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#1183 feat: bump Containerd patch release 1.7.22
  ansible/group_vars/all/defaults.yaml
Labels: feature, runs-e2e-tests

#1188 feat: bump the k8s version
  Dockerfile.devkit
  ansible/group_vars/all/defaults.yaml
  cmd/konvoy-image-wrapper/cmd/create-package-bundle.go
  images/common.yaml
Labels: feature, runs-e2e-tests

#1187 [release-2.5] fix: remove snapshot groups (#1124)
  pkg/packer/manifests/aws/packer.pkr.hcl
Labels: runs-e2e-tests

#1186 [release-2.8] fix: remove snapshot groups (#1124)
  pkg/packer/manifests/aws/packer.pkr.hcl
Labels: runs-e2e-tests

#1191 fix: enable installing cri-tools rpm from upstream repo
  ansible/roles/kubeadm/tasks/redhat.yaml
Labels: runs-aws-tests

#1189 chore(main): release 2.15.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending
