Repository mesosphere/konvoy-image-builder, pull requests merged in 2024-06, with the labels that each got.

#1049 chore(main): release 2.10.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#1099 fix: Enable unprivileged ports sysctl in containerd config
  ansible/roles/config/templates/config.toml.tmpl
Labels: fix

#1100 chore(main): release 2.10.1
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#1108 fix: bump Containerd patch release 1.6.33
  ansible/group_vars/all/defaults.yaml
Labels: fix, runs-e2e-tests

#1109 fix: bump Kubernetes patch release 1.29.6
  ansible/group_vars/all/defaults.yaml
  images/common.yaml
Labels: fix, runs-e2e-tests

#1110 chore(main): release 2.10.2
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#1111 fix: always downoad kubernetes images
  ansible/README.md
  ansible/group_vars/all/defaults.yaml
  ansible/provision.yaml
  docs/dev/changing-amis.md
  images/ami/flatcar.yaml
  images/ami/oracle-79.yaml
  images/ami/rhel-86.yaml
  images/ami/rhel-88.yaml
  images/ami/rocky-91.yaml
  images/ami/sles-15.yaml
  images/ami/ubuntu-1804.yaml
  images/ami/ubuntu-2004.yaml
  images/azure/flatcar.yaml
  images/azure/rhel-84.yaml
  images/azure/rocky-91.yaml
  images/azure/sles-15.yaml
  images/azure/ubuntu-1804.yaml
  images/azure/ubuntu-2004.yaml
  images/common.yaml
  images/gcp/ubuntu-1804.yaml
  images/gcp/ubuntu-2004.yaml
  images/generic/flatcar.yaml
  images/generic/oracle-7.yaml
  images/generic/oracle-8.yaml
  images/generic/sles-15.yaml
  images/generic/ubuntu-1804.yaml
  images/generic/ubuntu-2004.yaml
  images/ova/flatcar.yaml
  images/ova/rhel-86.yaml
  images/ova/rhel-88.yaml
  images/ova/rocky-91.yaml
  images/ova/ubuntu-2004.yaml
Labels: fix
