Repository mesosphere/konvoy-image-builder, pull requests merged in 2024-12, with the labels that each got.

#1240 fix: Nvidia kernel versions in air-gapped bundle
  bundles/redhat8.10/packages.txt.gotmpl
  bundles/redhat8.8/packages.txt.gotmpl
Labels: fix, runs-aws-tests

#1242 build: update azure-cli version
  requirements-devkit.txt
Labels: runs-azure-tests

#1245 feat: support ubuntu 22.04 for gcp images
  .github/workflows/gcp-e2e.yaml
  .github/workflows/release-gcp-template.yaml
  images/gcp/ubuntu-2204.yaml
Labels: feature, runs-gcp-tests

#1236 chore(main): release 2.20.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending
