Repository mesosphere/konvoy-image-builder, pull requests merged in 2024-02, with the labels that each got.

#989 chore: E2E tooling fixes.
  .github/workflows/aws-e2e.yaml
  .github/workflows/azure-e2e.yaml
  .github/workflows/build-devkit-image.yaml
  .github/workflows/gcp-e2e.yaml
  .github/workflows/podman-aws-e2e.yaml
  .github/workflows/release-ami.yaml
  .github/workflows/release-azure.yaml
  .github/workflows/release-gcp-template.yaml
  .github/workflows/release-kib.yaml
  .github/workflows/release-vsphere-template.yaml
  .github/workflows/vsphere-e2e.yaml
  test/infra/vsphere/packer-vsphere-airgap.yaml.tmpl
Labels: ignore-for-release, runs-e2e-tests

#981 fix: wrong vsphere config assignment - backport 2.5
  cmd/konvoy-image/cmd/vsphere.go
Labels: fix, runs-vsphere-tests

#996 fix: Update k8s debian package repositories to pkgs.k8s.io, bumps critools to 1.28
  ansible/group_vars/all/defaults.yaml
  ansible/group_vars/all/system.yaml
  ansible/roles/repo/tasks/debian.yaml
  images/common.yaml
Labels: fix, runs-e2e-tests

#1010 feat: bump Containerd to 1.6.28
  ansible/group_vars/all/defaults.yaml
Labels: feature, runs-e2e-tests

#1012 feat(k8s): Bump to 1.28.7
  ansible/group_vars/all/defaults.yaml
  images/common.yaml
Labels: feature, ready, runs-e2e-tests

#992 chore(main): release 2.9.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#1011 [release-2.5] [backport] fix: Update k8s debian package repositories to pkgs.k8s.io
  ansible/group_vars/all/defaults.yaml
  ansible/group_vars/all/system.yaml
  ansible/roles/repo/tasks/debian.yaml
Labels: runs-e2e-tests

#1014 [release-2.5] feat: update Containerd to 1.6.28
  ansible/group_vars/all/defaults.yaml
Labels: runs-e2e-tests

#986 [release-2.5] feat: Update kubernetes version to v1.26.14
  ansible/group_vars/all/defaults.yaml
  images/common.yaml
Labels: feature, runs-e2e-tests

#1018 e2e: remove problematic p2 instance
  magefile.go
Labels: runs-aws-tests

#1021 [backport-2.5] [release-2.5] ci: Set linked_clone to false during tests
  test/infra/vsphere/packer-vsphere-airgap.yaml.tmpl
Labels: fix, runs-vsphere-tests

#1019 fix: minor changes to support CRE
  ansible/group_vars/all/defaults.yaml
  ansible/roles/config/templates/config.toml.tmpl
Labels: runs-aws-tests

#1020 fix: update Packer to v1.10.1
  Dockerfile.devkit
Labels: fix, runs-e2e-tests
