Repository mesosphere/konvoy-image-builder, pull requests merged in 2024-05, with the labels that each got.

#1064 D2IQ-100548: add missing .aws/config file mount - main
  cmd/konvoy-image-wrapper/cmd/wrapper.go
Labels: needs-backport, runs-e2e-tests

#1073 feat: bumps nvidia driver to new LTSB
  ansible/group_vars/all/defaults.yaml
Labels: feature, runs-aws-tests

#1076 fix: use pkgs.k8s.io deb repo for k8s 1.24
  ansible/group_vars/all/defaults.yaml
  ansible/group_vars/all/system.yaml
  ansible/roles/repo/tasks/debian.yaml
Labels: fix

#1081 fix: clean yum cache after adding repos
  ansible/roles/repo/tasks/redhat.yaml
Labels: fix, runs-aws-tests

#1087 fix(release-2.9): linter workflow due to golangci-lint in CI
  .golangci.yml
  cmd/konvoy-image-wrapper/cmd/create-package-bundle.go
  cmd/konvoy-image-wrapper/cmd/wrapper.go
  cmd/konvoy-image/cmd/aws.go
  cmd/konvoy-image/cmd/azure.go
  cmd/konvoy-image/cmd/build.go
  cmd/konvoy-image/cmd/gcp.go
  cmd/konvoy-image/cmd/generate.go
  cmd/konvoy-image/cmd/provision.go
  cmd/konvoy-image/cmd/vsphere.go
  pkg/app/utils.go
  pkg/logging/logger.go
Labels: fix

#1085 fix: clean yum cache after adding repos (#1081)
  ansible/roles/repo/tasks/redhat.yaml
Labels: fix

#1084 chore: bump dynamic-credential-provider to v0.5.3
  ansible/group_vars/all/defaults.yaml
Labels: ignore-for-release

#1089 feat: update Kubernetes to v1.29.5
  ansible/group_vars/all/defaults.yaml
  bundles/ubuntu20.04/bundle.sh.gotmpl
  bundles/ubuntu20.04/packages.txt.gotmpl
  images/common.yaml
Labels: feature, runs-e2e-tests

#1072 feat: removes rhel 7.9 rhel 8.4 and centos 7.9
  .github/workflows/aws-e2e.yaml
  .github/workflows/gcp-e2e.yaml
  .github/workflows/release-ami.yaml
  .github/workflows/release-azure.yaml
  .github/workflows/release-vsphere-template.yaml
  .github/workflows/vsphere-e2e.yaml
  ansible/roles/containerd/tasks/redhat.yaml
  ansible/roles/gpu/tasks/nvidia-gpu-CentOS7.yaml
  ansible/roles/gpu/tasks/nvidia-gpu.yaml
  ansible/roles/providers/tasks/vmware.yml
  images/ami/centos-79.yaml
  images/ami/oracle-84.yaml
  images/ami/rhel-79.yaml
  images/ami/rhel-84.yaml
  images/azure/centos-79.yaml
  images/azure/oracle-79.yaml
  images/azure/oracle-84.yaml
  images/azure/rhel-79.yaml
  images/gcp/centos-79.yaml
  images/generic/centos-7.yaml
  images/ova/rhel-79.yaml
  images/ova/rhel-84.yaml
Labels: feature, runs-e2e-tests

#1090 ci: run tests on medium runners
  .github/workflows/aws-e2e.yaml
  .github/workflows/azure-e2e.yaml
  .github/workflows/gcp-e2e.yaml
  .github/workflows/release-ami.yaml
  .github/workflows/release-azure.yaml
  .github/workflows/release-gcp-template.yaml
  .github/workflows/release-vcd-template.yaml
  .github/workflows/release-vsphere-template.yaml
  .github/workflows/vsphere-e2e.yaml
Labels: runs-e2e-tests

#1095 fix: remove building bundles for unsupported OS
  bundles/centos7.9/bundle.sh.gotmpl
  bundles/centos7.9/packages.txt.gotmpl
  bundles/centos7.9/repo-templates/kubernetes.repo.gotmpl
  bundles/redhat7.9/bundle.sh.gotmpl
  bundles/redhat7.9/packages.txt.gotmpl
  bundles/redhat7.9/repo-templates/kubernetes.repo.gotmpl
  bundles/redhat8.4/bundle.sh.gotmpl
  bundles/redhat8.4/packages.txt.gotmpl
  bundles/redhat8.4/repo-templates/centos.repo
  bundles/redhat8.4/repo-templates/kubernetes.repo.gotmpl
  cmd/konvoy-image-wrapper/cmd/create-package-bundle.go
Labels: fix
