Repository mesosphere/konvoy-image-builder, pull requests merged in 2025-05, with the labels that each got.

#1303 fix(release-2.23): bump nvidia kernel headers for RHEL 8.10
  bundles/redhat8.10/packages.txt.gotmpl
Labels: fix, runs-aws-tests

#1305 [release-2.22] feat(k8s): Bump to latest patch 1.31.9
  ansible/group_vars/all/defaults.yaml
  images/common.yaml
Labels: ready, runs-e2e-tests

#1304 feat: Bump K8s to 1.33.1
  ansible/group_vars/all/defaults.yaml
  images/common.yaml
Labels: feature, runs-e2e-tests

#1298 chore(main): release 2.25.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending
