Repository mesosphere/konvoy-image-builder, pull requests merged in 2025-03, with the labels that each got.

#1265 [release-2.18] feat(k8s): Bump to latest patch 1.30.10
  ansible/group_vars/all/defaults.yaml
  images/common.yaml
Labels: feature, ready, runs-e2e-tests

#1266 [release-2.18] fix: kernel versions for Nvidia
  bundles/redhat8.10/packages.txt.gotmpl
  bundles/redhat8.8/packages.txt.gotmpl
Labels: fix, runs-aws-tests

#1268 feat: nvidia kernel headers fix
  bundles/redhat8.10/packages.txt.gotmpl
  bundles/redhat8.8/packages.txt.gotmpl
Labels: fix, runs-aws-tests

#1271 fix: allow using deprecated Rocky 9.1 AMI
  images/ami/rocky-91.yaml
  pkg/packer/manifests/aws/packer.pkr.hcl
Labels: fix

#1270 feat: download kubernetes images in the KIB container
  .github/workflows/podman-aws-e2e.yaml
  Dockerfile
  Dockerfile.devkit
  Makefile
  ansible/group_vars/all/defaults.yaml
  ansible/roles/images/tasks/main.yaml
  ansible/roles/images/tasks/upload.yaml
  ansible/roles/offline/tasks/upload.yaml
  hack/download-artifacts.sh
  magefile.go
  overrides/offline-fips.yaml
  overrides/offline.yaml
Labels: feature, runs-e2e-tests

#1273 [release-2.18 ] fix: allow using deprecated Rocky 9.1 AMI
  images/ami/rocky-91.yaml
  pkg/packer/manifests/aws/packer.pkr.hcl
Labels: fix

#1274 [release-2.22] fix: allow using deprecated Rocky 9.1 AMI
  images/ami/rocky-91.yaml
  pkg/packer/manifests/aws/packer.pkr.hcl
Labels: fix

#1275 fix(release-2.22): download kubernetes images in the KIB container (#1270)
  .github/workflows/podman-aws-e2e.yaml
  Dockerfile
  Dockerfile.devkit
  Makefile
  ansible/group_vars/all/defaults.yaml
  ansible/roles/images/tasks/main.yaml
  ansible/roles/images/tasks/upload.yaml
  ansible/roles/offline/tasks/upload.yaml
  bundles/redhat8.10/packages.txt.gotmpl
  bundles/redhat8.8/packages.txt.gotmpl
  hack/download-artifacts.sh
  magefile.go
  overrides/offline-fips.yaml
  overrides/offline.yaml
Labels: fix

#1276 feat(release-2.18): download kubernetes images in the KIB container (#1270)
  .github/workflows/podman-aws-e2e.yaml
  Dockerfile
  Dockerfile.devkit
  Makefile
  ansible/group_vars/all/defaults.yaml
  ansible/roles/images/tasks/main.yaml
  ansible/roles/images/tasks/upload.yaml
  ansible/roles/offline/tasks/upload.yaml
  bundles/redhat8.10/packages.txt.gotmpl
  hack/download-artifacts.sh
  magefile.go
  overrides/offline-fips.yaml
  overrides/offline.yaml
Labels: feature

#1272 fix: custom cloudinit script
  ansible/roles/providers/files/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceEc2Kubernetes.py
Labels: fix, runs-aws-tests

#1267 feat: bump the Kubernetes version to v1.32.3
  ansible/group_vars/all/defaults.yaml
  cmd/konvoy-image-wrapper/cmd/create-package-bundle.go
  hack/download-artifacts.sh
  images/common.yaml
Labels: feature, runs-e2e-tests

#1282 feat: backports embeded rpm changes
  Dockerfile
  Dockerfile.devkit
  Makefile
  ansible/group_vars/all/defaults.yaml
  ansible/roles/kubeadm/tasks/redhat.yaml
  ansible/roles/packages/tasks/redhat.yaml
  ansible/roles/providers/tasks/aws.yml
  bundles/redhat8.10/bundle.sh.gotmpl
  bundles/redhat8.10/packages.txt.gotmpl
  bundles/redhat8.10/repo-templates/kubernetes.repo.gotmpl
  cmd/konvoy-image-wrapper/cmd/create-package-bundle.go
  cmd/konvoy-image/cmd/create-package-bundle.go
  docs/cli/konvoy-image_create-package-bundle.md
  images/ami/rhel-810.yaml
  magefile.go
Labels: feature, runs-aws-tests

#1269 chore(main): release 2.23.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending
