Repository mesosphere/konvoy-image-builder, pull requests merged in 2025-02, with the labels that each got.

#1257 [stacked] fix: updates kernel headers for rhel 8.10 on AWS
  bundles/redhat8.10/packages.txt.gotmpl
Labels: runs-aws-tests

#1256 feat: bumps nvidia driver
  ansible/group_vars/all/defaults.yaml
  bundles/redhat8.10/packages.txt.gotmpl
Labels: feature, runs-aws-tests

#1258 chore(main): release 2.22.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#1259 fix: Update RHEL 8.8 kernel headers version
  bundles/redhat8.8/README.md
  bundles/redhat8.8/packages.txt.gotmpl
Labels: fix, runs-aws-tests

#1260 fix: Update RHEL 8.10 kernel packages version
  bundles/redhat8.10/README.md
Labels: fix, runs-aws-tests

#1261 chore(main): release 2.22.1
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#1262 fix: moves sysctl settings to a common place for preprovisioned and providers
  ansible/roles/config/tasks/main.yaml
  ansible/roles/providers/tasks/misc.yml
Labels: fix

#1263 chore(main): release 2.22.2
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending, runs-aws-tests
