Repository mesosphere/konvoy-image-builder, pull requests merged in 2025-08, with the labels that each got.

#1329 chore(main): release 2.28.2
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#1331 chore(main): release 2.28.3
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending

#1332 fix: update cache after adding offline repository
  ansible/roles/packages/tasks/debian.yaml
  ansible/roles/repo/tasks/debian-offline.yaml
Labels: fix

#1333 fix: change update cache logic for debian
  ansible/roles/packages/tasks/debian.yaml
  ansible/roles/repo/tasks/debian-offline.yaml
Labels: fix, runs-aws-tests
