Repository mesosphere/konvoy-image-builder, pull requests merged in 2025-01, with the labels that each got.

#1246 fix: ubuntu 22.04 gpu support
  ansible/roles/gpu/tasks/nvidia-gpu-Ubuntu.yaml
  ansible/roles/gpu/tasks/nvidia-gpu-Ubuntu20.yaml
  ansible/roles/gpu/tasks/nvidia-gpu.yaml
Labels: fix, runs-aws-tests

#1248 fix: drop ubuntu 18.04
  .github/workflows/aws-e2e.yaml
  .github/workflows/gcp-e2e.yaml
  ansible/molecule/default/molecule.yml
  cmd/konvoy-image/cmd/create-package-bundle.go
  docs/cli/konvoy-image_create-package-bundle.md
  docs/dev/nvidia-gpu.md
  images/ami/ubuntu-1804.yaml
  images/azure/ubuntu-1804.yaml
  images/gcp/ubuntu-1804.yaml
  images/generic/ubuntu-1804.yaml
  pkg/packer/manifests/aws/packer.pkr.hcl
  pkg/packer/manifests/azure/packer.pkr.hcl
  pkg/packer/manifests/gcp/packer.pkr.hcl
Labels: fix, runs-aws-tests

#1244 feat: Support creating ubuntu 22.04 AMI for AWS
  .github/workflows/aws-e2e.yaml
  .github/workflows/release-ami.yaml
  ansible/roles/gpu/tasks/nvidia-gpu-Ubuntu.yaml
  ansible/roles/gpu/tasks/nvidia-gpu-Ubuntu20.yaml
  ansible/roles/gpu/tasks/nvidia-gpu.yaml
  images/ami/ubuntu-2204.yaml
Labels: feature, runs-aws-tests

#1247 feat: Azure add support for ubuntu-22.04
  .github/workflows/azure-e2e.yaml
  .github/workflows/release-azure.yaml
  images/azure/ubuntu-2204.yaml
Labels: feature, runs-azure-tests

#1251 feat: removes cloud-init pins
  ansible/roles/providers/files/cloud-init-features.patch
  ansible/roles/providers/tasks/aws.yml
  ansible/roles/providers/tasks/misc.yml
  bundles/redhat8.10/packages.txt.gotmpl
  bundles/ubuntu20.04/bundle.sh.gotmpl
  images/ami/ubuntu-2004.yaml
  images/ami/ubuntu-2204.yaml
Labels: feature

#1252 feat: Remove VCD from konvoy-image-builder
  .github/composite/vcd-e2e/action.yaml
  .github/workflows/release-vcd-template.yaml
  .github/workflows/release-vsphere-template.yaml
  test/infra/Makefile
  test/infra/vcd/bastion.tf
  test/infra/vcd/upload-template.sh
  test/infra/vcd/variables.tf
Labels: feature

#1250 feat: create package bundle for ubuntu 22.04
  .github/workflows/aws-e2e.yaml
  .github/workflows/vsphere-e2e.yaml
  bundles/ubuntu22.04/bundle.sh.gotmpl
  bundles/ubuntu22.04/packages.txt.gotmpl
  cmd/konvoy-image-wrapper/cmd/create-package-bundle.go
Labels: feature, runs-vsphere-tests, runs-aws-tests

#1254 fix: remove support for sles-15
  .github/workflows/aws-e2e.yaml
  .github/workflows/release-ami.yaml
  ansible/molecule/default/molecule.yml
  ansible/molecule/ec2_full/molecule.yml
  ansible/molecule/ec2_gpu/molecule.yml
  docs/dev/nvidia-gpu.md
  images/ami/sles-15.yaml
  images/azure/sles-15.yaml
  images/generic/sles-15.yaml
  magefile.go
Labels: fix, runs-aws-tests

#1243 fix: fail on curl errors in devkit build
  Dockerfile.devkit
Labels: fix, runs-aws-tests

#1255 feat: adds custom datasource for ubuntu 22.04
  .github/workflows/lint.yml
  ansible/roles/providers/files/etc/cloud/cloud.cfg.d/90_dpkg.cfg
  ansible/roles/providers/files/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceEc2Kubernetes.py
  ansible/roles/providers/tasks/aws.yml
  ansible/roles/providers/tasks/main.yml
Labels: feature

#1249 chore(main): release 2.21.0
  CHANGELOG.md
Labels: ignore-for-release, autorelease: pending
